import { Player } from './shared/player';

export const PLAYERS: Player[] = [
	{id: 1, name : "Cam Newton", position : "QB", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
	{id: 2, name : "Aaron Rodgers", position : "QB", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
	{id: 3, name : "Russell Wilson", position : "QB", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"}, 
	{id: 4, name : "Drew Brees", position : "QB", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
	{id: 5, name : "Matthew Stafford", position : "QB", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"}, 
	{id: 6, name : "Ben Roethlisberger", position : "QB", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
	{id: 7, name : "Tom Brady", position : "QB", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
	{id: 8, name : "Matt Ryan", position : "QB", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
	{id: 9, name : "Philip Rivers", position : "QB", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
	{id: 10, name : "Eli Manning", position : "QB", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
	{id: 11, name : "Derek Carr", position : "QB", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
	{id: 12, name : "Kirk Cousins", position : "QB", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
	{id: 13, name : "Dak Prescott", position : "QB", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"},
	{id: 14, name : "Jameis Winston", position : "QB", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
	{id: 15, name : "Deshaun Watson", position : "QB", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
	{id: 16, name : "Jared Goff", position : "QB", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
	{id: 17, name : "Carson Wentz", position : "QB", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
	{id: 18, name : "Baker Mayfield", position : "QB", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
	{id: 19, name : "Mitchell Trubisky", position : "QB", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
	{id: 20, name : "Jimmy Garoppolo", position : "QB", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
	{id: 21, name : "Lamar Jackson", position : "QB", team: "Baltimore Ravens", logo : "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg", alt : "Bal"},
	{id: 22, name : "Patrick Mahomes", position : "QB", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
	{id: 23, name : "Andrew Luck", position : "QB", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
	{id: 24, name : "Kyler Murray", position : "QB", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
	{id: 25, name : "David Johnson", position : "RB", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
	{id: 26, name : "Lamar Miller", position : "RB", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
	{id: 27, name : "Todd Gurley", position : "RB", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
	{id: 28, name : "Carlos Hyde", position : "RB", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
	{id: 29, name : "Kareem Hunt", position : "RB", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
	{id: 30, name : "Ezekiel Elliott", position : "RB", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"}, 
	{id: 31, name : "James Conner", position : "RB", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
	{id: 32, name : "Devonta Freeman", position : "RB", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
	{id: 33, name : "Latavius Murray", position : "RB", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
	{id: 34, name : "Alvin Kamara", position : "RB", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"}, 
	{id: 35, name : "LeSean McCoy", position : "RB", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
	{id: 36, name : "Devin Singletary", position : "RB", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
	{id: 37, name : "David Montgomery", position : "RB", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
	{id: 38, name : "Jordan Howard", position : "RB", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
	{id: 39, name : "Melvin Gordon", position : "RB", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
	{id: 40, name : "Leonard Fournette", position : "RB", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
	{id: 41, name : "Aaron Jones", position : "RB", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
	{id: 42, name : "Le'Veon Bell", position : "RB", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
	{id: 43, name : "Christian McCaffrey", position : "RB", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
	{id: 44, name : "Damien Williams", position : "RB", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
	{id: 45, name : "Austin Ekeler", position : "RB", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
	{id: 46, name : "Miles Sanders", position : "RB", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
	{id: 47, name : "Josh Jacobs", position : "RB", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
	{id: 48, name : "Dalvin Cook", position : "RB", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
	{id: 49, name : "Joe Mixon", position : "RB", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
	{id: 50, name : "Sony Michel", position : "RB", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
	{id: 51, name : "James White", position : "RB", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
	{id: 52, name : "Kerryon Johnson", position : "RB", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"},
	{id: 53, name : "Adrian Peterson", position : "RB", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
	{id: 54, name : "Derrius Guice", position : "RB", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
	{id: 55, name : "Chris Thompson", position : "RB", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
	{id: 56, name : "Dion Lewis", position : "RB", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
	{id: 57, name : "T.J. Yeldon", position : "RB", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
	{id: 58, name : "Duke Johnson", position : "RB", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
	{id: 59, name : "Kenyan Drake", position : "RB", team: "Miami Dolphins", logo : "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg", alt : "Mia"},
	{id: 60, name : "Kalen Ballage", position : "RB", team: "Miami Dolphins", logo : "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg", alt : "Mia"},
	{id: 61, name : "Saquon Barkley", position : "RB", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
	{id: 62, name : "Derrick Henry", position : "RB", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
	{id: 63, name : "Nyheim Hines", position : "RB", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
	{id: 64, name : "T.J. Yeldon", position : "RB", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
	{id: 65, name : "Marlon Mack", position : "RB", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
	{id: 66, name : "Matt Breida", position : "RB", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
	{id: 67, name : "Tevin Coleman", position : "RB", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
	{id: 68, name : "Peyton Barber", position : "RB", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
	{id: 69, name : "Chris Carson", position : "RB", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
	{id: 70, name : "Tarik Cohen", position : "RB", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
	{id: 71, name : "Darrell Henderson", position : "RB", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
	{id: 72, name : "Mark Ingram", position : "RB", team: "Baltimore Ravens", logo : "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg", alt : "Bal"},
	{id: 73, name : "Rashaad Penny", position : "RB", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
	{id: 74, name : "Phillip Lindsay", position : "RB", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
	{id: 75, name : "Ronald Jones", position : "RB", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
	{id: 76, name : "Nick Chubb", position : "RB", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
	{id: 77, name : "Royce Freeman", position : "RB", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
	{id: 78, name : "Jalen Richard", position : "RB", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
	{id: 79, name : "Antonio Brown", position : "WR", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
	{id: 80, name : "Odell Beckham", position : "WR", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
	{id: 81, name : "Julio Jones", position : "WR", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
	{id: 82, name : "DeAndre Hopkins", position : "WR", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
	{id: 83, name : "Allen Robinson", position : "WR", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
	{id: 84, name : "A.J. Green", position : "WR", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
	{id: 85, name : "Keenan Allen", position : "WR", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
	{id: 86, name : "Alshon Jeffery", position : "WR", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
	{id: 87, name : "Tyler Lockett", position : "WR", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
	{id: 88, name : "Mike Evans", position : "WR", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
	{id: 89, name : "Chris Godwin", position : "WR", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
	{id: 90, name : "Michael Thomas", position : "WR", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
	{id: 91, name : "T.Y. Hilton", position : "WR", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
	{id: 92, name : "Amari Cooper", position : "WR", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"},
	{id: 93, name : "Brandin Cooks", position : "WR", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
	{id: 94, name : "DeSean Jackson", position : "WR", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
	{id: 95, name : "Larry Fitzgerald", position : "WR", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
	{id: 96, name : "Christian Kirk", position : "WR", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
	{id: 97, name : "Emmanuel Sanders", position : "WR", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
	{id: 98, name : "Davante Adams", position : "WR", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
	{id: 99, name : "Jamison Crowder", position : "WR", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
	{id: 100, name : "John Brown", position : "WR", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
	{id: 101, name : "Golden Tate", position : "WR", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
	{id: 102, name : "Mike Williams", position : "WR", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
	{id: 103, name : "Jarvis Landry", position : "WR", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
	{id: 104, name : "Kenny Stills", position : "WR", team: "Miami Dolphins", logo : "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg", alt : "Mia"},
	{id: 105, name : "Tyreek Hill", position : "WR", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
	{id: 106, name : "Stefon Diggs", position : "WR", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
	{id: 107, name : "Adam Thielen", position : "WR", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
	{id: 108, name : "Marvin Jones", position : "WR", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"},
	{id: 109, name : "Kenny Golladay", position : "WR", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"},
	{id: 110, name : "JuJu Smith-Schuster", position : "WR", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
	{id: 111, name : "Robby Anderson", position : "WR", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
	{id: 112, name : "Devin Funchess", position : "WR", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
	{id: 113, name : "D.J. Moore", position : "WR", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
	{id: 114, name : "Nelson Agholor", position : "WR", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
	{id: 115, name : "Cooper Kupp", position : "WR", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
	{id: 116, name : "Robert Woods", position : "WR", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
	{id: 117, name : "Sammy Watkins", position : "WR", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
	{id: 118, name : "Marquise Goodwin", position : "WR", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
	{id: 119, name : "Paul Richardson", position : "WR", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
	{id: 120, name : "Corey Davis", position : "WR", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
	{id: 121, name : "Will Fuller", position : "WR", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
	{id: 122, name : "Dede Westbrook", position : "WR", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
	{id: 123, name : "Calvin Ridley", position : "WR", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
	{id: 124, name : "Tyler Boyd", position : "WR", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
	{id: 125, name : "Julian Edelman", position : "WR", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
	{id: 126, name : "Josh Gordon", position : "WR", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
	{id: 127, name : "Quincy Enunwa", position : "WR", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
	{id: 128, name : "Tre'Quan Smith", position : "WR", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
	{id: 129, name : "Courtland Sutton", position : "WR", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
	{id: 130, name : "Sterling Shepard", position : "WR", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
	{id: 131, name : "Dante Pettis", position : "WR", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
	{id: 132, name : "Michael Gallup", position : "WR", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"},
	{id: 133, name : "Curtis Samuel", position : "WR", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
	{id: 134, name : "D.K. Metcalf", position : "WR", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
	{id: 135, name : "Donte Moncrief", position : "WR", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
	{id: 136, name : "James Washington", position : "WR", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
	{id: 137, name : "Keke Coutee", position : "WR", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
	{id: 138, name : "Tyrell Williams", position : "WR", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
	{id: 139, name : "Geronimo Allison", position : "WR", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
	{id: 140, name : "Marquez Valdes-Scantling", position : "WR", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
	{id: 141, name : "Anthony Miller", position : "WR", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
	{id: 142, name : "Adam Humphries", position : "WR", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
	{id: 143, name : "Jordan Reed", position : "TE", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
	{id: 145, name : "Greg Olsen", position : "TE", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
	{id: 146, name : "Travis Kelce", position : "TE", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
	{id: 147, name : "Jimmy Graham", position : "TE", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
	{id: 148, name : "Delanie Walker", position : "TE", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
	{id: 149, name : "Tyler Eifert", position : "TE", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
	{id: 150, name : "Jack Doyle", position : "TE", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
	{id: 151, name : "Zach Ertz", position : "TE", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
	{id: 152, name : "Kyle Rudolph", position : "TE", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
	{id: 153, name : "Eric Ebron", position : "TE", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
	{id: 154, name : "Evan Engram", position : "TE", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
	{id: 155, name : "Cameron Brate", position : "TE", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
	{id: 156, name : "Vernon Davis", position : "TE", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
	{id: 157, name : "O.J. Howard", position : "TE", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
	{id: 158, name : "George Kittle", position : "TE", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
	{id: 159, name : "Trey Burton", position : "TE", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
	{id: 160, name : "David Njoku", position : "TE", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
	{id: 161, name : "Austin Hooper", position : "TE", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
	{id: 162, name : "Hunter Henry", position : "TE", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
	{id: 163, name : "Jared Cook", position : "TE", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
	{id: 164, name : "Vance McDonald", position : "TE", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"}
];