import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Player } from '../shared/player';
import { Team } from '../shared/team';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const players = [
		{id: 1, name : "Cam Newton", position : "QB", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
		{id: 2, name : "Aaron Rodgers", position : "QB", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
		{id: 3, name : "Russell Wilson", position : "QB", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"}, 
		{id: 4, name : "Drew Brees", position : "QB", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
		{id: 5, name : "Matthew Stafford", position : "QB", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"}, 
		{id: 6, name : "Ben Roethlisberger", position : "QB", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
		{id: 7, name : "Tom Brady", position : "QB", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
		{id: 8, name : "Matt Ryan", position : "QB", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
		{id: 9, name : "Philip Rivers", position : "QB", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
		{id: 10, name : "Daniel Jones", position : "QB", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
		{id: 11, name : "Derek Carr", position : "QB", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
		{id: 12, name : "Kirk Cousins", position : "QB", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
		{id: 13, name : "Dak Prescott", position : "QB", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"},
		{id: 14, name : "Jameis Winston", position : "QB", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
		{id: 15, name : "Deshaun Watson", position : "QB", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
		{id: 16, name : "Jared Goff", position : "QB", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
		{id: 17, name : "Carson Wentz", position : "QB", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
		{id: 18, name : "Baker Mayfield", position : "QB", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
		{id: 19, name : "Mitchell Trubisky", position : "QB", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
		{id: 20, name : "Jimmy Garoppolo", position : "QB", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
		{id: 21, name : "Lamar Jackson", position : "QB", team: "Baltimore Ravens", logo : "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg", alt : "Bal"},
		{id: 22, name : "Patrick Mahomes", position : "QB", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
		{id: 23, name : "Josh Allen", position : "QB", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
		{id: 24, name : "Kyler Murray", position : "QB", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
		{id: 25, name : "David Johnson", position : "RB", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
		{id: 26, name : "Gus Edwards", position : "RB", team: "Baltimore Ravens", logo : "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg", alt : "Bal"},
		{id: 27, name : "Todd Gurley", position : "RB", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
		{id: 28, name : "Carlos Hyde", position : "RB", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
		{id: 29, name : "Kareem Hunt", position : "RB", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
		{id: 30, name : "Ezekiel Elliott", position : "RB", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"}, 
		{id: 31, name : "James Conner", position : "RB", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
		{id: 32, name : "Devonta Freeman", position : "RB", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
		{id: 33, name : "Latavius Murray", position : "RB", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
		{id: 34, name : "Alvin Kamara", position : "RB", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"}, 
		{id: 35, name : "LeSean McCoy", position : "RB", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
		{id: 36, name : "Devin Singletary", position : "RB", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
		{id: 37, name : "David Montgomery", position : "RB", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
		{id: 38, name : "Jordan Howard", position : "RB", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
		{id: 39, name : "Melvin Gordon", position : "RB", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
		{id: 40, name : "Leonard Fournette", position : "RB", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
		{id: 41, name : "Aaron Jones", position : "RB", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
		{id: 42, name : "Le'Veon Bell", position : "RB", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
		{id: 43, name : "Christian McCaffrey", position : "RB", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
		{id: 44, name : "Damien Williams", position : "RB", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
		{id: 45, name : "Austin Ekeler", position : "RB", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
		{id: 46, name : "Miles Sanders", position : "RB", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
		{id: 47, name : "Josh Jacobs", position : "RB", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
		{id: 48, name : "Dalvin Cook", position : "RB", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
		{id: 49, name : "Joe Mixon", position : "RB", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
		{id: 50, name : "Sony Michel", position : "RB", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
		{id: 51, name : "James White", position : "RB", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
		{id: 52, name : "Kerryon Johnson", position : "RB", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"},
		{id: 53, name : "Adrian Peterson", position : "RB", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
		{id: 54, name : "Derrius Guice", position : "RB", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
		{id: 55, name : "Chris Thompson", position : "RB", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
		{id: 56, name : "Dion Lewis", position : "RB", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
		{id: 57, name : "Frank Gore", position : "RB", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
		{id: 58, name : "Duke Johnson", position : "RB", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
		{id: 59, name : "Kenyan Drake", position : "RB", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari" },
		{id: 60, name : "Kalen Ballage", position : "RB", team: "Miami Dolphins", logo : "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg", alt : "Mia"},
		{id: 61, name : "Saquon Barkley", position : "RB", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
		{id: 62, name : "Derrick Henry", position : "RB", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
		{id: 63, name : "Nyheim Hines", position : "RB", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
		{id: 64, name : "T.J. Yeldon", position : "RB", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
		{id: 65, name : "Marlon Mack", position : "RB", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
		{id: 66, name : "Matt Breida", position : "RB", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
		{id: 67, name : "Tevin Coleman", position : "RB", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
		{id: 68, name : "Peyton Barber", position : "RB", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
		{id: 69, name : "Chris Carson", position : "RB", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
		{id: 70, name : "Tarik Cohen", position : "RB", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
		{id: 71, name : "Darrell Henderson", position : "RB", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
		{id: 72, name : "Mark Ingram", position : "RB", team: "Baltimore Ravens", logo : "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg", alt : "Bal"},
		{id: 73, name : "Rashaad Penny", position : "RB", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
		{id: 74, name : "Phillip Lindsay", position : "RB", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
		{id: 75, name : "Ronald Jones", position : "RB", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
		{id: 76, name : "Nick Chubb", position : "RB", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
		{id: 77, name : "Royce Freeman", position : "RB", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
		{id: 78, name : "Jalen Richard", position : "RB", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
		{id: 79, name : "Phillip Dorsett", position : "WR", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"}, 
		{id: 80, name : "Odell Beckham", position : "WR", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
		{id: 81, name : "Julio Jones", position : "WR", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
		{id: 82, name : "DeAndre Hopkins", position : "WR", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
		{id: 83, name : "Allen Robinson", position : "WR", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
		{id: 84, name : "A.J. Green", position : "WR", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
		{id: 85, name : "Keenan Allen", position : "WR", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
		{id: 86, name : "Alshon Jeffery", position : "WR", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
		{id: 87, name : "Tyler Lockett", position : "WR", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
		{id: 88, name : "Mike Evans", position : "WR", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
		{id: 89, name : "Chris Godwin", position : "WR", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
		{id: 90, name : "Michael Thomas", position : "WR", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
		{id: 91, name : "T.Y. Hilton", position : "WR", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
		{id: 92, name : "Amari Cooper", position : "WR", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"},
		{id: 93, name : "Brandin Cooks", position : "WR", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
		{id: 94, name : "DeSean Jackson", position : "WR", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
		{id: 95, name : "Larry Fitzgerald", position : "WR", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
		{id: 96, name : "Christian Kirk", position : "WR", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
		{id: 97, name : "Emmanuel Sanders", position : "WR", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
		{id: 98, name : "Davante Adams", position : "WR", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
		{id: 99, name : "Jamison Crowder", position : "WR", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
		{id: 100, name : "John Brown", position : "WR", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
		{id: 101, name : "Golden Tate", position : "WR", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
		{id: 102, name : "Mike Williams", position : "WR", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
		{id: 103, name : "Jarvis Landry", position : "WR", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
		{id: 104, name : "Preston Williams", position : "WR", team: "Miami Dolphins", logo : "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg", alt : "Mia"},
		{id: 105, name : "Tyreek Hill", position : "WR", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
		{id: 106, name : "Stefon Diggs", position : "WR", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
		{id: 107, name : "Adam Thielen", position : "WR", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
		{id: 108, name : "Marvin Jones", position : "WR", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"},
		{id: 109, name : "Kenny Golladay", position : "WR", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"},
		{id: 110, name : "JuJu Smith-Schuster", position : "WR", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
		{id: 111, name : "Robby Anderson", position : "WR", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
		{id: 112, name : "Devin Funchess", position : "WR", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
		{id: 113, name : "D.J. Moore", position : "WR", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
		{id: 114, name : "Nelson Agholor", position : "WR", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
		{id: 115, name : "Cooper Kupp", position : "WR", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
		{id: 116, name : "Robert Woods", position : "WR", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
		{id: 117, name : "Sammy Watkins", position : "WR", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
		{id: 118, name : "Marquise Goodwin", position : "WR", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
		{id: 119, name : "Paul Richardson", position : "WR", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
		{id: 120, name : "Corey Davis", position : "WR", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
		{id: 121, name : "Will Fuller", position : "WR", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
		{id: 122, name : "Dede Westbrook", position : "WR", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
		{id: 123, name : "Calvin Ridley", position : "WR", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
		{id: 124, name : "Tyler Boyd", position : "WR", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
		{id: 125, name : "Julian Edelman", position : "WR", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
		{id: 126, name : "Josh Gordon", position : "WR", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
		{id: 127, name : "Quincy Enunwa", position : "WR", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
		{id: 128, name : "Tre'Quan Smith", position : "WR", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
		{id: 129, name : "Courtland Sutton", position : "WR", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
		{id: 130, name : "Sterling Shepard", position : "WR", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
		{id: 131, name : "Dante Pettis", position : "WR", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
		{id: 132, name : "Michael Gallup", position : "WR", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"},
		{id: 133, name : "Curtis Samuel", position : "WR", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
		{id: 134, name : "D.K. Metcalf", position : "WR", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
		{id: 135, name : "Donte Moncrief", position : "WR", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
		{id: 136, name : "James Washington", position : "WR", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
		{id: 137, name : "Keke Coutee", position : "WR", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
		{id: 138, name : "Tyrell Williams", position : "WR", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
		{id: 139, name : "Geronimo Allison", position : "WR", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
		{id: 140, name : "Marquez Valdes-Scantling", position : "WR", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
		{id: 141, name : "Anthony Miller", position : "WR", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
		{id: 142, name : "Adam Humphries", position : "WR", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
		{id: 143, name : "Jordan Reed", position : "TE", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
		{id: 145, name : "Greg Olsen", position : "TE", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
		{id: 146, name : "Travis Kelce", position : "TE", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
		{id: 147, name : "Jimmy Graham", position : "TE", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
		{id: 148, name : "Delanie Walker", position : "TE", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
		{id: 149, name : "Tyler Eifert", position : "TE", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
		{id: 150, name : "Jack Doyle", position : "TE", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
		{id: 151, name : "Zach Ertz", position : "TE", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
		{id: 152, name : "Kyle Rudolph", position : "TE", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
		{id: 153, name : "Eric Ebron", position : "TE", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
		{id: 154, name : "Evan Engram", position : "TE", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
		{id: 155, name : "Cameron Brate", position : "TE", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
		{id: 156, name : "Vernon Davis", position : "TE", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
		{id: 157, name : "O.J. Howard", position : "TE", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
		{id: 158, name : "George Kittle", position : "TE", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
		{id: 159, name : "Trey Burton", position : "TE", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
		{id: 160, name : "David Njoku", position : "TE", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
		{id: 161, name : "Austin Hooper", position : "TE", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
		{id: 162, name : "Hunter Henry", position : "TE", team: "Los Angeles Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
		{id: 163, name : "Jared Cook", position : "TE", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
		{id: 164, name : "Vance McDonald", position : "TE", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
		{id: 165, name : "Darren Waller", position : "TE", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"}
	];
	const teams = [];
	const stats = [
	  {
	    "Player": "Patrick Mahomes",
	    "Team": "KC",
	    "ATT": 580.7,
	    "CMP": 379.2,
	    "YDS": 4776.1,
	    "TDS": 35.9,
	    "INTS": 13.3,
	    "ATT_1": 52.5,
	    "YDS_1": 219.6,
	    "TDS_1": 1.9,
	    "FL": 2,
	    "FPTS": 337.5
	  },
	  {
	    "Player": "Deshaun Watson",
	    "Team": "HOU",
	    "ATT": 509.5,
	    "CMP": 336.2,
	    "YDS": 4047.4,
	    "TDS": 26.2,
	    "INTS": 12,
	    "ATT_1": 95.3,
	    "YDS_1": 553.5,
	    "TDS_1": 4.3,
	    "FL": 2.7,
	    "FPTS": 318.7
	  },
	  {
	    "Player": "Aaron Rodgers",
	    "Team": "GB",
	    "ATT": 596.2,
	    "CMP": 378.4,
	    "YDS": 4315.3,
	    "TDS": 29.8,
	    "INTS": 7.6,
	    "ATT_1": 46.3,
	    "YDS_1": 260.5,
	    "TDS_1": 2.1,
	    "FL": 2.1,
	    "FPTS": 310.6
	  },
	  {
	    "Player": "Andrew Luck",
	    "Team": "IND",
	    "ATT": 605.4,
	    "CMP": 397.8,
	    "YDS": 4497.5,
	    "TDS": 33.4,
	    "INTS": 14.2,
	    "ATT_1": 51.8,
	    "YDS_1": 217.1,
	    "TDS_1": 1.4,
	    "FL": 2.6,
	    "FPTS": 310.1
	  },
	  {
	    "Player": "Matt Ryan",
	    "Team": "ATL",
	    "ATT": 585.5,
	    "CMP": 394.5,
	    "YDS": 4632.8,
	    "TDS": 30.1,
	    "INTS": 10.6,
	    "ATT_1": 48.2,
	    "YDS_1": 132.6,
	    "TDS_1": 1.5,
	    "FL": 2,
	    "FPTS": 302.6
	  },
	  {
	    "Player": "Cam Newton",
	    "Team": "CAR",
	    "ATT": 515,
	    "CMP": 336.5,
	    "YDS": 3775.4,
	    "TDS": 24.6,
	    "INTS": 13.7,
	    "ATT_1": 113.2,
	    "YDS_1": 546.1,
	    "TDS_1": 4.4,
	    "FL": 1.7,
	    "FPTS": 300
	  },
	  {
	    "Player": "Drew Brees",
	    "Team": "NO",
	    "ATT": 538.5,
	    "CMP": 387.2,
	    "YDS": 4338.2,
	    "TDS": 30.5,
	    "INTS": 8.8,
	    "ATT_1": 24.8,
	    "YDS_1": 40.2,
	    "TDS_1": 1.9,
	    "FL": 1.6,
	    "FPTS": 290.3
	  },
	  {
	    "Player": "Jameis Winston",
	    "Team": "TB",
	    "ATT": 560.7,
	    "CMP": 356.5,
	    "YDS": 4430.0,
	    "TDS": 27.4,
	    "INTS": 16.3,
	    "ATT_1": 57.2,
	    "YDS_1": 277.1,
	    "TDS_1": 1.6,
	    "FL": 2.7,
	    "FPTS": 286.3
	  },
	  {
	    "Player": "Baker Mayfield",
	    "Team": "CLE",
	    "ATT": 564.7,
	    "CMP": 362.5,
	    "YDS": 4335.3,
	    "TDS": 30.8,
	    "INTS": 14.6,
	    "ATT_1": 47,
	    "YDS_1": 180.8,
	    "TDS_1": 0.9,
	    "FL": 2.4,
	    "FPTS": 285.8
	  },
	  {
	    "Player": "Dak Prescott",
	    "Team": "DAL",
	    "ATT": 522.1,
	    "CMP": 344.3,
	    "YDS": 3856.2,
	    "TDS": 23.7,
	    "INTS": 10.9,
	    "ATT_1": 68,
	    "YDS_1": 311.2,
	    "TDS_1": 5.3,
	    "FL": 2.3,
	    "FPTS": 285.6
	  },
	  {
	    "Player": "Jared Goff",
	    "Team": "LAR",
	    "ATT": 551,
	    "CMP": 352.1,
	    "YDS": 4378.1,
	    "TDS": 30.2,
	    "INTS": 11.7,
	    "ATT_1": 31.1,
	    "YDS_1": 102.8,
	    "TDS_1": 1.2,
	    "FL": 2.2,
	    "FPTS": 285.5
	  },
	  {
	    "Player": "Carson Wentz",
	    "Team": "PHI",
	    "ATT": 568.4,
	    "CMP": 376.6,
	    "YDS": 4237.3,
	    "TDS": 30,
	    "INTS": 12.3,
	    "ATT_1": 52.3,
	    "YDS_1": 192,
	    "TDS_1": 1,
	    "FL": 2.6,
	    "FPTS": 284.8
	  },
	  {
	    "Player": "Ben Roethlisberger",
	    "Team": "PIT",
	    "ATT": 619.1,
	    "CMP": 406,
	    "YDS": 4636.9,
	    "TDS": 29.4,
	    "INTS": 15.2,
	    "ATT_1": 23.3,
	    "YDS_1": 75.3,
	    "TDS_1": 1.2,
	    "FL": 1.8,
	    "FPTS": 284.1
	  },
	  {
	    "Player": "Lamar Jackson",
	    "Team": "BAL",
	    "ATT": 431.9,
	    "CMP": 255.9,
	    "YDS": 2988.4,
	    "TDS": 16.9,
	    "INTS": 10.7,
	    "ATT_1": 172.5,
	    "YDS_1": 886.9,
	    "TDS_1": 6.1,
	    "FL": 4.9,
	    "FPTS": 281.3
	  },
	  {
	    "Player": "Russell Wilson",
	    "Team": "SEA",
	    "ATT": 453.2,
	    "CMP": 292.2,
	    "YDS": 3565.9,
	    "TDS": 27.8,
	    "INTS": 9.5,
	    "ATT_1": 73,
	    "YDS_1": 381.5,
	    "TDS_1": 2,
	    "FL": 2.1,
	    "FPTS": 281.1
	  },
	  {
	    "Player": "Tom Brady",
	    "Team": "NE",
	    "ATT": 580.3,
	    "CMP": 380,
	    "YDS": 4353.1,
	    "TDS": 29.2,
	    "INTS": 10.7,
	    "ATT_1": 20.8,
	    "YDS_1": 38.8,
	    "TDS_1": 1,
	    "FL": 1.5,
	    "FPTS": 276.4
	  },
	  {
	    "Player": "Kirk Cousins",
	    "Team": "MIN",
	    "ATT": 578.4,
	    "CMP": 397.8,
	    "YDS": 4183.6,
	    "TDS": 27.9,
	    "INTS": 12.1,
	    "ATT_1": 38.5,
	    "YDS_1": 134.1,
	    "TDS_1": 1.9,
	    "FL": 2.4,
	    "FPTS": 274.4
	  },
	  {
	    "Player": "Mitchell Trubisky",
	    "Team": "CHI",
	    "ATT": 511.3,
	    "CMP": 332.8,
	    "YDS": 3760.7,
	    "TDS": 25.1,
	    "INTS": 13,
	    "ATT_1": 65.9,
	    "YDS_1": 377.9,
	    "TDS_1": 2.4,
	    "FL": 2.5,
	    "FPTS": 272.1
	  },
	  {
	    "Player": "Philip Rivers",
	    "Team": "LAC",
	    "ATT": 546.3,
	    "CMP": 360.1,
	    "YDS": 4367.4,
	    "TDS": 29.6,
	    "INTS": 12.2,
	    "ATT_1": 13.5,
	    "YDS_1": 25.2,
	    "TDS_1": 0.2,
	    "FL": 1.4,
	    "FPTS": 269.8
	  },
	  {
	    "Player": "Kyler Murray",
	    "Team": "ARI",
	    "ATT": 537.4,
	    "CMP": 331.8,
	    "YDS": 3694.6,
	    "TDS": 21.6,
	    "INTS": 14.3,
	    "ATT_1": 107,
	    "YDS_1": 506.9,
	    "TDS_1": 3.2,
	    "FL": 3.2,
	    "FPTS": 268.9
	  },
	  {
	    "Player": "Josh Allen",
	    "Team": "BUF",
	    "ATT": 479.7,
	    "CMP": 270.6,
	    "YDS": 3210.1,
	    "TDS": 17.3,
	    "INTS": 14.4,
	    "ATT_1": 104.8,
	    "YDS_1": 664.1,
	    "TDS_1": 6.3,
	    "FL": 2.9,
	    "FPTS": 267.1
	  },
	  {
	    "Player": "Jimmy Garoppolo",
	    "Team": "SF",
	    "ATT": 519.2,
	    "CMP": 333.8,
	    "YDS": 4073.9,
	    "TDS": 25.1,
	    "INTS": 14.2,
	    "ATT_1": 37.7,
	    "YDS_1": 122.2,
	    "TDS_1": 1.3,
	    "FL": 2.1,
	    "FPTS": 250.8
	  },
	  {
	    "Player": "Matthew Stafford",
	    "Team": "DET",
	    "ATT": 560,
	    "CMP": 368.8,
	    "YDS": 3971.3,
	    "TDS": 24.2,
	    "INTS": 11.6,
	    "ATT_1": 28.9,
	    "YDS_1": 78.5,
	    "TDS_1": 0.7,
	    "FL": 1.7,
	    "FPTS": 241.4
	  },
	  {
	    "Player": "Derek Carr",
	    "Team": "OAK",
	    "ATT": 570.3,
	    "CMP": 379.4,
	    "YDS": 4098.3,
	    "TDS": 23.6,
	    "INTS": 12.2,
	    "ATT_1": 24.5,
	    "YDS_1": 68.7,
	    "TDS_1": 0.6,
	    "FL": 2.1,
	    "FPTS": 240.6
	  },
	  {
	    "Player": "Andy Dalton",
	    "Team": "CIN",
	    "ATT": 533.6,
	    "CMP": 331.2,
	    "YDS": 3684.9,
	    "TDS": 24,
	    "INTS": 13.6,
	    "ATT_1": 32.9,
	    "YDS_1": 119.9,
	    "TDS_1": 0.9,
	    "FL": 1.7,
	    "FPTS": 229.9
	  },
	  {
	    "Player": "Sam Darnold",
	    "Team": "NYJ",
	    "ATT": 530.7,
	    "CMP": 320,
	    "YDS": 3645.3,
	    "TDS": 22.6,
	    "INTS": 15.8,
	    "ATT_1": 48,
	    "YDS_1": 187.5,
	    "TDS_1": 1.6,
	    "FL": 2.3,
	    "FPTS": 228
	  },
	  {
	    "Player": "Marcus Mariota",
	    "Team": "TEN",
	    "ATT": 446.9,
	    "CMP": 294,
	    "YDS": 3269.0,
	    "TDS": 18.3,
	    "INTS": 12.6,
	    "ATT_1": 70.4,
	    "YDS_1": 358.9,
	    "TDS_1": 2.6,
	    "FL": 2.4,
	    "FPTS": 225.6
	  },
	  {
	    "Player": "Nick Foles",
	    "Team": "JAC",
	    "ATT": 531.8,
	    "CMP": 338.8,
	    "YDS": 3777.9,
	    "TDS": 21.5,
	    "INTS": 13.3,
	    "ATT_1": 33.1,
	    "YDS_1": 76.5,
	    "TDS_1": 0.9,
	    "FL": 2,
	    "FPTS": 219.9
	  },
	  {
	    "Player": "Eli Manning",
	    "Team": "NYG",
	    "ATT": 497.4,
	    "CMP": 314.4,
	    "YDS": 3382.5,
	    "TDS": 19,
	    "INTS": 10.7,
	    "ATT_1": 20.7,
	    "YDS_1": 50.3,
	    "TDS_1": 1,
	    "FL": 2.5,
	    "FPTS": 196
	  },
	  {
    	"Player": "Daniel Jones",
	    "Team": "NYG",
	    "ATT": 87.3,
	    "CMP": 54,
	    "YDS": 730.1,
	    "TDS": 3.9,
	    "INTS": 3.1,
	    "ATT_1": 5.8,
	    "YDS_1": 33.7,
	    "TDS_1": 0.3,
	    "FL": 0.4,
	    "FPTS": 42.9
  	  },
	  {
	    "Player": "Saquon Barkley",
	    "Team": "NYG",
	    "ATT": 269,
	    "YDS": 1253.7,
	    "TDS": 9.6,
	    "REC": 87.6,
	    "YDS_1": 705.5,
	    "TDS_1": 3.4,
	    "FL": 1.5,
	    "FPTS": 358.6
	  },
	  {
	    "Player": "Christian McCaffrey",
	    "Team": "CAR",
	    "ATT": 215.8,
	    "YDS": 1044.8,
	    "TDS": 6.7,
	    "REC": 97.2,
	    "YDS_1": 824.3,
	    "TDS_1": 5.1,
	    "FL": 1.8,
	    "FPTS": 351.6
	  },
	  {
	    "Player": "Alvin Kamara",
	    "Team": "NO",
	    "ATT": 194.7,
	    "YDS": 913.8,
	    "TDS": 9.6,
	    "REC": 87.4,
	    "YDS_1": 771.3,
	    "TDS_1": 4.6,
	    "FL": 1.5,
	    "FPTS": 338.3
	  },
	  {
	    "Player": "Ezekiel Elliott",
	    "Team": "DAL",
	    "ATT": 294.3,
	    "YDS": 1295.2,
	    "TDS": 8.9,
	    "REC": 67,
	    "YDS_1": 515.7,
	    "TDS_1": 2.6,
	    "FL": 2.2,
	    "FPTS": 312.5
	  },
	  {
	    "Player": "Le'Veon Bell",
	    "Team": "NYJ",
	    "ATT": 257.1,
	    "YDS": 1106.4,
	    "TDS": 7.6,
	    "REC": 64,
	    "YDS_1": 514.9,
	    "TDS_1": 2.6,
	    "FL": 1.8,
	    "FPTS": 284.1
	  },
	  {
	    "Player": "David Johnson",
	    "Team": "ARI",
	    "ATT": 247,
	    "YDS": 1000.4,
	    "TDS": 7.4,
	    "REC": 59.3,
	    "YDS_1": 565.3,
	    "TDS_1": 3.1,
	    "FL": 2.4,
	    "FPTS": 274.3
	  },
	  {
	    "Player": "Dalvin Cook",
	    "Team": "MIN",
	    "ATT": 245.8,
	    "YDS": 1113.0,
	    "TDS": 6.6,
	    "REC": 59.5,
	    "YDS_1": 455.8,
	    "TDS_1": 2.2,
	    "FL": 2.9,
	    "FPTS": 263.5
	  },
	  {
	    "Player": "James Conner",
	    "Team": "PIT",
	    "ATT": 228.1,
	    "YDS": 1016.9,
	    "TDS": 9.5,
	    "REC": 53.5,
	    "YDS_1": 435.2,
	    "TDS_1": 1.6,
	    "FL": 1.7,
	    "FPTS": 261.6
	  },
	  {
	    "Player": "Todd Gurley",
	    "Team": "LAR",
	    "ATT": 218.4,
	    "YDS": 1009.4,
	    "TDS": 9.9,
	    "REC": 46.3,
	    "YDS_1": 423.9,
	    "TDS_1": 2.6,
	    "FL": 1.5,
	    "FPTS": 261.4
	  },
	  {
	    "Player": "Joe Mixon",
	    "Team": "CIN",
	    "ATT": 245.7,
	    "YDS": 1144.0,
	    "TDS": 8.4,
	    "REC": 47.1,
	    "YDS_1": 354.8,
	    "TDS_1": 1.2,
	    "FL": 1.5,
	    "FPTS": 251.5
	  },
	  {
	    "Player": "Nick Chubb",
	    "Team": "CLE",
	    "ATT": 243.8,
	    "YDS": 1165.0,
	    "TDS": 9.2,
	    "REC": 32.7,
	    "YDS_1": 251.6,
	    "TDS_1": 1.6,
	    "FL": 1,
	    "FPTS": 236.8
	  },
	  {
	    "Player": "Kerryon Johnson",
	    "Team": "DET",
	    "ATT": 212.4,
	    "YDS": 997.4,
	    "TDS": 6.5,
	    "REC": 49.5,
	    "YDS_1": 354.9,
	    "TDS_1": 1.9,
	    "FL": 1.7,
	    "FPTS": 231.4
	  },
	  {
	    "Player": "Leonard Fournette",
	    "Team": "JAC",
	    "ATT": 249.5,
	    "YDS": 968.1,
	    "TDS": 7.5,
	    "REC": 43.6,
	    "YDS_1": 362,
	    "TDS_1": 1.5,
	    "FL": 1.2,
	    "FPTS": 228
	  },
	  {
	    "Player": "Melvin Gordon",
	    "Team": "LAC",
	    "ATT": 179.9,
	    "YDS": 812.7,
	    "TDS": 7.5,
	    "REC": 42.8,
	    "YDS_1": 390.3,
	    "TDS_1": 2.5,
	    "FL": 1.2,
	    "FPTS": 221.1
	  },
	  {
	    "Player": "Aaron Jones",
	    "Team": "GB",
	    "ATT": 195.4,
	    "YDS": 969.1,
	    "TDS": 8.5,
	    "REC": 37.3,
	    "YDS_1": 287.5,
	    "TDS_1": 1.4,
	    "FL": 1.4,
	    "FPTS": 219.4
	  },
	  {
	    "Player": "Josh Jacobs",
	    "Team": "OAK",
	    "ATT": 214,
	    "YDS": 938.7,
	    "TDS": 6.5,
	    "REC": 42.3,
	    "YDS_1": 353,
	    "TDS_1": 1.6,
	    "FL": 1.6,
	    "FPTS": 217.1
	  },
	  {
	    "Player": "Derrick Henry",
	    "Team": "TEN",
	    "ATT": 268.6,
	    "YDS": 1240.6,
	    "TDS": 10.4,
	    "REC": 17,
	    "YDS_1": 129.1,
	    "TDS_1": 0.3,
	    "FL": 1.3,
	    "FPTS": 215.8
	  },
	  {
	    "Player": "Damien Williams",
	    "Team": "KC",
	    "ATT": 151,
	    "YDS": 728.8,
	    "TDS": 6.9,
	    "REC": 46.5,
	    "YDS_1": 368.8,
	    "TDS_1": 3.4,
	    "FL": 1.4,
	    "FPTS": 215.6
	  },
	  {
	    "Player": "Chris Carson",
	    "Team": "SEA",
	    "ATT": 239.6,
	    "YDS": 1113.4,
	    "TDS": 8.2,
	    "REC": 27.3,
	    "YDS_1": 220.8,
	    "TDS_1": 1,
	    "FL": 1.9,
	    "FPTS": 212
	  },
	  {
	    "Player": "Devonta Freeman",
	    "Team": "ATL",
	    "ATT": 202.9,
	    "YDS": 874,
	    "TDS": 6.9,
	    "REC": 41.5,
	    "YDS_1": 331.5,
	    "TDS_1": 1.8,
	    "FL": 1.3,
	    "FPTS": 211.7
	  },
	  {
	    "Player": "James White",
	    "Team": "NE",
	    "ATT": 67.2,
	    "YDS": 285.7,
	    "TDS": 2.5,
	    "REC": 71.1,
	    "YDS_1": 629.6,
	    "TDS_1": 4.1,
	    "FL": 0.5,
	    "FPTS": 201.2
	  },
	  {
	    "Player": "Marlon Mack",
	    "Team": "IND",
	    "ATT": 234.6,
	    "YDS": 1061.9,
	    "TDS": 7.9,
	    "REC": 26,
	    "YDS_1": 187.4,
	    "TDS_1": 0.9,
	    "FL": 1.5,
	    "FPTS": 201
	  },
	  {
	    "Player": "David Montgomery",
	    "Team": "CHI",
	    "ATT": 204.1,
	    "YDS": 888.1,
	    "TDS": 6.4,
	    "REC": 33.7,
	    "YDS_1": 275.6,
	    "TDS_1": 1.4,
	    "FL": 1.9,
	    "FPTS": 193.1
	  },
	  {
	    "Player": "Mark Ingram",
	    "Team": "BAL",
	    "ATT": 221.5,
	    "YDS": 940.3,
	    "TDS": 6.7,
	    "REC": 32.5,
	    "YDS_1": 247.6,
	    "TDS_1": 0.8,
	    "FL": 1.7,
	    "FPTS": 193
	  },
	  {
	    "Player": "Phillip Lindsay",
	    "Team": "DEN",
	    "ATT": 185.7,
	    "YDS": 899,
	    "TDS": 6.4,
	    "REC": 34.5,
	    "YDS_1": 249.3,
	    "TDS_1": 1,
	    "FL": 1,
	    "FPTS": 191.8
	  },
	  {
	    "Player": "Sony Michel",
	    "Team": "NE",
	    "ATT": 236.7,
	    "YDS": 1076.9,
	    "TDS": 9.2,
	    "REC": 11.3,
	    "YDS_1": 85.9,
	    "TDS_1": 0.3,
	    "FL": 1.5,
	    "FPTS": 181.6
	  },
	  {
	    "Player": "Kenyan Drake",
	    "Team": "ARI",
	    "ATT": 143,
	    "YDS": 609.6,
	    "TDS": 3.8,
	    "REC": 46.8,
	    "YDS_1": 393.1,
	    "TDS_1": 2.3,
	    "FL": 1.4,
	    "FPTS": 181.1
	  },
	  {
	    "Player": "Tarik Cohen",
	    "Team": "CHI",
	    "ATT": 84.1,
	    "YDS": 352.2,
	    "TDS": 2.2,
	    "REC": 59,
	    "YDS_1": 550.8,
	    "TDS_1": 3.1,
	    "FL": 1.7,
	    "FPTS": 177.8
	  },
	  {
	    "Player": "Duke Johnson",
	    "Team": "HOU",
	    "ATT": 122.3,
	    "YDS": 575,
	    "TDS": 3.2,
	    "REC": 45.9,
	    "YDS_1": 410.9,
	    "TDS_1": 2.2,
	    "FL": 0.7,
	    "FPTS": 175.1
	  },
	  {
	    "Player": "Derrius Guice",
	    "Team": "WAS",
	    "ATT": 178.5,
	    "YDS": 800.3,
	    "TDS": 5.6,
	    "REC": 29.6,
	    "YDS_1": 249.8,
	    "TDS_1": 0.9,
	    "FL": 1.6,
	    "FPTS": 170.3
	  },
	  {
	    "Player": "Tevin Coleman",
	    "Team": "SF",
	    "ATT": 168.1,
	    "YDS": 777,
	    "TDS": 4.8,
	    "REC": 29,
	    "YDS_1": 262.1,
	    "TDS_1": 1.5,
	    "FL": 0.8,
	    "FPTS": 168.7
	  },
	  {
	    "Player": "Austin Ekeler",
	    "Team": "LAC",
	    "ATT": 122.3,
	    "YDS": 564.1,
	    "TDS": 3.4,
	    "REC": 40.5,
	    "YDS_1": 378.5,
	    "TDS_1": 2.1,
	    "FL": 1,
	    "FPTS": 165.9
	  },
	  {
	    "Player": "Matt Breida",
	    "Team": "SF",
	    "ATT": 152.2,
	    "YDS": 666.4,
	    "TDS": 4,
	    "REC": 31.9,
	    "YDS_1": 288.9,
	    "TDS_1": 1.6,
	    "FL": 1,
	    "FPTS": 158.7
	  },
	  {
	    "Player": "Miles Sanders",
	    "Team": "PHI",
	    "ATT": 157.8,
	    "YDS": 620.6,
	    "TDS": 4.4,
	    "REC": 32.7,
	    "YDS_1": 260.7,
	    "TDS_1": 1.3,
	    "FL": 1.4,
	    "FPTS": 152.6
	  },
	  {
	    "Player": "Peyton Barber",
	    "Team": "TB",
	    "ATT": 180.7,
	    "YDS": 741,
	    "TDS": 4.7,
	    "REC": 22.1,
	    "YDS_1": 148.1,
	    "TDS_1": 0.6,
	    "FL": 1.4,
	    "FPTS": 139.6
	  },
	  {
	    "Player": "Latavius Murray",
	    "Team": "NO",
	    "ATT": 164,
	    "YDS": 648,
	    "TDS": 6.4,
	    "REC": 17.1,
	    "YDS_1": 112.8,
	    "TDS_1": 0.4,
	    "FL": 0.8,
	    "FPTS": 132.2
	  },
	  {
	    "Player": "Rashaad Penny",
	    "Team": "SEA",
	    "ATT": 150.9,
	    "YDS": 683.9,
	    "TDS": 4,
	    "REC": 18.6,
	    "YDS_1": 143.4,
	    "TDS_1": 0.8,
	    "FL": 1,
	    "FPTS": 127.8
	  },
	  {
	    "Player": "Chris Thompson",
	    "Team": "WAS",
	    "ATT": 56.1,
	    "YDS": 232.9,
	    "TDS": 0.9,
	    "REC": 49.8,
	    "YDS_1": 384.6,
	    "TDS_1": 1.9,
	    "FL": 0.8,
	    "FPTS": 126.3
	  },
	  {
	    "Player": "LeSean McCoy",
	    "Team": "KC",
	    "ATT": 124.9,
	    "YDS": 484.9,
	    "TDS": 4,
	    "REC": 27.9,
	    "YDS_1": 212.1,
	    "TDS_1": 1.1,
	    "FL": 1.1,
	    "FPTS": 125.7
	  },
	  {
	    "Player": "Devin Singletary",
	    "Team": "BUF",
	    "ATT": 157.8,
	    "YDS": 570.3,
	    "TDS": 3.4,
	    "REC": 24,
	    "YDS_1": 205.5,
	    "TDS_1": 0.8,
	    "FL": 1,
	    "FPTS": 125
	  },
	  {
	    "Player": "Kalen Ballage",
	    "Team": "MIA",
	    "ATT": 127.4,
	    "YDS": 628.6,
	    "TDS": 3.8,
	    "REC": 23.7,
	    "YDS_1": 175.1,
	    "TDS_1": 0.4,
	    "FL": 2.4,
	    "FPTS": 124.5
	  },
	  {
	    "Player": "Dion Lewis",
	    "Team": "TEN",
	    "ATT": 94.4,
	    "YDS": 367.6,
	    "TDS": 2,
	    "REC": 41.4,
	    "YDS_1": 297.2,
	    "TDS_1": 1,
	    "FL": 0.7,
	    "FPTS": 124.4
	  },
	  {
	    "Player": "Darrell Henderson",
	    "Team": "LAR",
	    "ATT": 117.1,
	    "YDS": 525.4,
	    "TDS": 3.6,
	    "REC": 24.2,
	    "YDS_1": 207.3,
	    "TDS_1": 1,
	    "FL": 1.3,
	    "FPTS": 122.1
	  },
	  {
	    "Player": "Jalen Richard",
	    "Team": "OAK",
	    "ATT": 48.4,
	    "YDS": 227.3,
	    "TDS": 1.3,
	    "REC": 47,
	    "YDS_1": 402.9,
	    "TDS_1": 1.2,
	    "FL": 1.6,
	    "FPTS": 121.8
	  },
	  {
	    "Player": "Jordan Howard",
	    "Team": "PHI",
	    "ATT": 152.6,
	    "YDS": 652,
	    "TDS": 5,
	    "REC": 15.8,
	    "YDS_1": 106.6,
	    "TDS_1": 0.3,
	    "FL": 1.1,
	    "FPTS": 121.5
	  },
	  {
	    "Player": "Nyheim Hines",
	    "Team": "IND",
	    "ATT": 73.6,
	    "YDS": 295.3,
	    "TDS": 1.5,
	    "REC": 39.4,
	    "YDS_1": 294.9,
	    "TDS_1": 1.3,
	    "FL": 0.7,
	    "FPTS": 113.5
	  },
	  {
	    "Player": "Jaylen Samuels",
	    "Team": "PIT",
	    "ATT": 74.8,
	    "YDS": 313.2,
	    "TDS": 2,
	    "REC": 32.2,
	    "YDS_1": 259.9,
	    "TDS_1": 2,
	    "FL": 0.7,
	    "FPTS": 112
	  },
	  {
	    "Player": "Isaiah Crowell",
	    "Team": "OAK",
	    "ATT": 135,
	    "YDS": 570,
	    "TDS": 4.7,
	    "REC": 16.8,
	    "YDS_1": 115,
	    "TDS_1": 0.2,
	    "FL": 1.5,
	    "FPTS": 111.5
	  },
	  {
	    "Player": "Royce Freeman",
	    "Team": "DEN",
	    "ATT": 160.3,
	    "YDS": 594.4,
	    "TDS": 3.9,
	    "REC": 15.1,
	    "YDS_1": 101.7,
	    "TDS_1": 0.3,
	    "FL": 1,
	    "FPTS": 108.1
	  },
	  {
	    "Player": "Frank Gore",
	    "Team": "BUF",
	    "ATT": 120,
	    "YDS": 585.9,
	    "TDS": 3.2,
	    "REC": 14.4,
	    "YDS_1": 122.7,
	    "TDS_1": 0.5,
	    "FL": 0.8,
	    "FPTS": 105.6
	  },
	  {
	    "Player": "Giovani Bernard",
	    "Team": "CIN",
	    "ATT": 75.3,
	    "YDS": 288.6,
	    "TDS": 1.9,
	    "REC": 33.9,
	    "YDS_1": 259.2,
	    "TDS_1": 0.7,
	    "FL": 0.4,
	    "FPTS": 103.4
	  },
	  {
	    "Player": "Ito Smith",
	    "Team": "ATL",
	    "ATT": 100.6,
	    "YDS": 408.4,
	    "TDS": 3.3,
	    "REC": 23.4,
	    "YDS_1": 160.2,
	    "TDS_1": 0.7,
	    "FL": 0.8,
	    "FPTS": 102.7
	  },
	  {
	    "Player": "Jamaal Williams",
	    "Team": "GB",
	    "ATT": 106.9,
	    "YDS": 414.9,
	    "TDS": 2.7,
	    "REC": 22.6,
	    "YDS_1": 177.1,
	    "TDS_1": 0.6,
	    "FL": 0.6,
	    "FPTS": 100.6
	  },
	  {
	    "Player": "Lamar Miller",
	    "Team": "HOU",
	    "ATT": 112.5,
	    "YDS": 484.5,
	    "TDS": 2.9,
	    "REC": 18.5,
	    "YDS_1": 136,
	    "TDS_1": 0.6,
	    "FL": 2.6,
	    "FPTS": 96
	  },
	  {
	    "Player": "Ronald Jones II",
	    "Team": "TB",
	    "ATT": 122.2,
	    "YDS": 435.7,
	    "TDS": 3.3,
	    "REC": 17.9,
	    "YDS_1": 125.6,
	    "TDS_1": 0.4,
	    "FL": 0.8,
	    "FPTS": 95
	  },
	  {
	    "Player": "Kareem Hunt",
	    "Team": "CLE",
	    "ATT": 83.9,
	    "YDS": 356,
	    "TDS": 2.9,
	    "REC": 18.5,
	    "YDS_1": 172.7,
	    "TDS_1": 1.1,
	    "FL": 0.5,
	    "FPTS": 94.2
	  },
	  {
	    "Player": "Carlos Hyde",
	    "Team": "HOU",
	    "ATT": 131.3,
	    "YDS": 441.9,
	    "TDS": 3.2,
	    "REC": 13.3,
	    "YDS_1": 85.9,
	    "TDS_1": 0.2,
	    "FL": 1,
	    "FPTS": 84.1
	  },
	  {
	    "Player": "T.J. Yeldon",
	    "Team": "BUF",
	    "ATT": 60,
	    "YDS": 239,
	    "TDS": 1.2,
	    "REC": 25.3,
	    "YDS_1": 222.5,
	    "TDS_1": 1.1,
	    "FL": 0.6,
	    "FPTS": 83.6
	  },
	  {
	    "Player": "Adrian Peterson",
	    "Team": "WAS",
	    "ATT": 110.5,
	    "YDS": 427.4,
	    "TDS": 2.9,
	    "REC": 12.3,
	    "YDS_1": 95.8,
	    "TDS_1": 0.3,
	    "FL": 0.9,
	    "FPTS": 81.9
	  },
	  {
	    "Player": "Damien Harris",
	    "Team": "NE",
	    "ATT": 99.6,
	    "YDS": 367.6,
	    "TDS": 3,
	    "REC": 13.7,
	    "YDS_1": 116.9,
	    "TDS_1": 0.5,
	    "FL": 1,
	    "FPTS": 81.5
	  },
	  {
	    "Player": "Justice Hill",
	    "Team": "BAL",
	    "ATT": 78.8,
	    "YDS": 322.1,
	    "TDS": 2.3,
	    "REC": 17.5,
	    "YDS_1": 134.8,
	    "TDS_1": 0.6,
	    "FL": 0.9,
	    "FPTS": 79.2
	  },
	  {
	    "Player": "Justin Jackson",
	    "Team": "LAC",
	    "ATT": 84,
	    "YDS": 332.5,
	    "TDS": 2.2,
	    "REC": 15.5,
	    "YDS_1": 124.6,
	    "TDS_1": 0.4,
	    "FL": 0.2,
	    "FPTS": 76.4
	  },
	  {
	    "Player": "Ty Montgomery",
	    "Team": "NYJ",
	    "ATT": 70.3,
	    "YDS": 244.8,
	    "TDS": 1.8,
	    "REC": 19.8,
	    "YDS_1": 159.2,
	    "TDS_1": 0.7,
	    "FL": 0.8,
	    "FPTS": 73.5
	  },
	  {
	    "Player": "Alexander Mattison",
	    "Team": "MIN",
	    "ATT": 79.3,
	    "YDS": 307.7,
	    "TDS": 2.2,
	    "REC": 15.2,
	    "YDS_1": 113.6,
	    "TDS_1": 0.5,
	    "FL": 0.9,
	    "FPTS": 71.7
	  },
	  {
	    "Player": "Ryquell Armstead",
	    "Team": "JAC",
	    "ATT": 68.8,
	    "YDS": 267.6,
	    "TDS": 1.7,
	    "REC": 17,
	    "YDS_1": 133.8,
	    "TDS_1": 0.5,
	    "FL": 0.4,
	    "FPTS": 69.4
	  },
	  {
	    "Player": "Mike Davis",
	    "Team": "CAR",
	    "ATT": 61.7,
	    "YDS": 270.9,
	    "TDS": 2.2,
	    "REC": 15.6,
	    "YDS_1": 111.2,
	    "TDS_1": 0.4,
	    "FL": 0.5,
	    "FPTS": 68.1
	  },
	  {
	    "Player": "Gus Edwards",
	    "Team": "BAL",
	    "ATT": 94.3,
	    "YDS": 454.5,
	    "TDS": 2.9,
	    "REC": 2.6,
	    "YDS_1": 20,
	    "TDS_1": 0.1,
	    "FL": 0.5,
	    "FPTS": 66.6
	  },
	  {
	    "Player": "Rodney Anderson",
	    "Team": "CIN",
	    "ATT": 54.5,
	    "YDS": 252,
	    "TDS": 1.7,
	    "REC": 15,
	    "YDS_1": 130,
	    "TDS_1": 0.8,
	    "FL": 1,
	    "FPTS": 66.1
	  },
	  {
	    "Player": "Devontae Booker",
	    "Team": "DEN",
	    "ATT": 35.7,
	    "YDS": 160.5,
	    "TDS": 1.1,
	    "REC": 23.1,
	    "YDS_1": 186.1,
	    "TDS_1": 0.5,
	    "FL": 1,
	    "FPTS": 65.7
	  },
	  {
	    "Player": "Theo Riddick",
	    "Team": "DEN",
	    "ATT": 31.5,
	    "YDS": 136.9,
	    "TDS": 0.6,
	    "REC": 26.4,
	    "YDS_1": 183.9,
	    "TDS_1": 0.5,
	    "FL": 0.7,
	    "FPTS": 63.9
	  },
	  {
	    "Player": "Jerick McKinnon",
	    "Team": "SF",
	    "ATT": 51.5,
	    "YDS": 227.5,
	    "TDS": 1.2,
	    "REC": 17.2,
	    "YDS_1": 159,
	    "TDS_1": 0.6,
	    "FL": 1.4,
	    "FPTS": 63.7
	  },
	  {
	    "Player": "Chase Edmonds",
	    "Team": "ARI",
	    "ATT": 52.8,
	    "YDS": 222.5,
	    "TDS": 1.5,
	    "REC": 13.3,
	    "YDS_1": 103.1,
	    "TDS_1": 0.2,
	    "FL": 0.4,
	    "FPTS": 55.6
	  },
	  {
	    "Player": "Kyle Juszczyk",
	    "Team": "SF",
	    "ATT": 8,
	    "YDS": 28.2,
	    "TDS": 0.4,
	    "REC": 23.8,
	    "YDS_1": 219.6,
	    "TDS_1": 0.9,
	    "FL": 0.9,
	    "FPTS": 54.9
	  },
	  {
	    "Player": "Corey Clement",
	    "Team": "PHI",
	    "ATT": 40.6,
	    "YDS": 178.6,
	    "TDS": 1.4,
	    "REC": 14.6,
	    "YDS_1": 114.4,
	    "TDS_1": 0.4,
	    "FL": 0.3,
	    "FPTS": 54.4
	  },
	  {
	    "Player": "Dare Ogunbowale",
	    "Team": "TB",
	    "ATT": 46.8,
	    "YDS": 157.3,
	    "TDS": 1,
	    "REC": 16.7,
	    "YDS_1": 129.8,
	    "TDS_1": 0.5,
	    "FL": 0.3,
	    "FPTS": 53.5
	  },
	  {
	    "Player": "Ty Johnson",
	    "Team": "DET",
	    "ATT": 52.4,
	    "YDS": 201.5,
	    "TDS": 1.1,
	    "REC": 14,
	    "YDS_1": 101.9,
	    "TDS_1": 0.4,
	    "FL": 0.3,
	    "FPTS": 52.4
	  },
	  {
	    "Player": "Tony Pollard",
	    "Team": "DAL",
	    "ATT": 58.2,
	    "YDS": 216,
	    "TDS": 1.5,
	    "REC": 11.2,
	    "YDS_1": 78.5,
	    "TDS_1": 0.3,
	    "FL": 0.2,
	    "FPTS": 51.1
	  },
	  {
	    "Player": "Wayne Gallman",
	    "Team": "NYG",
	    "ATT": 54,
	    "YDS": 215.2,
	    "TDS": 1.3,
	    "REC": 11.7,
	    "YDS_1": 84.2,
	    "TDS_1": 0.2,
	    "FL": 0.8,
	    "FPTS": 48.9
	  },
	  {
	    "Player": "Darwin Thompson",
	    "Team": "KC",
	    "ATT": 50.1,
	    "YDS": 197.9,
	    "TDS": 1.3,
	    "REC": 10.2,
	    "YDS_1": 76.9,
	    "TDS_1": 0.6,
	    "FL": 0.3,
	    "FPTS": 48.3
	  },
	  {
	    "Player": "Devine Ozigbo",
	    "Team": "JAC",
	    "ATT": 36.3,
	    "YDS": 186.8,
	    "TDS": 1.2,
	    "REC": 10.6,
	    "YDS_1": 88.8,
	    "TDS_1": 0.4,
	    "FL": 0.3,
	    "FPTS": 47.4
	  },
	  {
	    "Player": "Rex Burkhead",
	    "Team": "NE",
	    "ATT": 44.7,
	    "YDS": 139,
	    "TDS": 1.4,
	    "REC": 11.6,
	    "YDS_1": 99.7,
	    "TDS_1": 0.6,
	    "FL": 0.4,
	    "FPTS": 46.6
	  },
	  {
	    "Player": "Dontrell Hilliard",
	    "Team": "CLE",
	    "ATT": 35.9,
	    "YDS": 120,
	    "TDS": 0.6,
	    "REC": 15.4,
	    "YDS_1": 123.3,
	    "TDS_1": 0.6,
	    "FL": 0.2,
	    "FPTS": 46.2
	  },
	  {
	    "Player": "Malcolm Brown",
	    "Team": "LAR",
	    "ATT": 49.1,
	    "YDS": 200.6,
	    "TDS": 1.5,
	    "REC": 7.5,
	    "YDS_1": 50.7,
	    "TDS_1": 0.2,
	    "FL": 0.3,
	    "FPTS": 41.7
	  },
	  {
	    "Player": "Benny Snell Jr.",
	    "Team": "PIT",
	    "ATT": 42,
	    "YDS": 163.3,
	    "TDS": 1.3,
	    "REC": 9.1,
	    "YDS_1": 78.8,
	    "TDS_1": 0.4,
	    "FL": 0.9,
	    "FPTS": 41.5
	  },
	  {
	    "Player": "Darren Sproles",
	    "Team": "PHI",
	    "ATT": 25.6,
	    "YDS": 89.1,
	    "TDS": 0.3,
	    "REC": 15.6,
	    "YDS_1": 129.4,
    	"TDS_1": 0.4,
    	"FL": 0.1,
    	"FPTS": 41.4
  	  },
	  {
	    "Player": "Bryce Love",
	    "Team": "WAS",
	    "ATT": 40.4,
	    "YDS": 168.4,
	    "TDS": 1.2,
	    "REC": 8.3,
	    "YDS_1": 73.9,
	    "TDS_1": 0.3,
	    "FL": 0.7,
	    "FPTS": 40.2
	  },
	  {
	    "Player": "C.J. Prosise",
	    "Team": "SEA",
	    "ATT": 15.7,
	    "YDS": 69,
	    "TDS": 0.3,
	    "REC": 14.4,
	    "YDS_1": 119.3,
	    "TDS_1": 0.7,
	    "FL": 0.1,
	    "FPTS": 39.2
	  },
	  {
	    "Player": "Brian Hill",
	    "Team": "ATL",
	    "ATT": 37.6,
	    "YDS": 187.9,
	    "TDS": 1.3,
	    "REC": 7.2,
	    "YDS_1": 52.5,
	    "TDS_1": 0.2,
	    "FL": 0.5,
	    "FPTS": 39.2
	  },
	  {
	    "Player": "Darius Jackson",
	    "Team": "IND",
	    "ATT": 42.7,
	    "YDS": 186,
	    "TDS": 1.2,
	    "REC": 7.5,
	    "YDS_1": 60.9,
	    "TDS_1": 0.2,
	    "FL": 1,
	    "FPTS": 38.7
	  },
	  {
	    "Player": "DeAndre Washington",
	    "Team": "OAK",
	    "ATT": 51.9,
	    "YDS": 180.6,
	    "TDS": 1.1,
	    "REC": 7.4,
	    "YDS_1": 59.7,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 38.5
	  },
	  {
	    "Player": "Bilal Powell",
	    "Team": "NYJ",
	    "ATT": 27.6,
	    "YDS": 169.6,
	    "TDS": 0.8,
	    "REC": 8.4,
	    "YDS_1": 67.2,
	    "TDS_1": 0.2,
	    "FL": 0.2,
	    "FPTS": 37.5
	  },
	  {
	    "Player": "Dexter Williams",
	    "Team": "GB",
	    "ATT": 32.3,
	    "YDS": 132.9,
	    "TDS": 1,
	    "REC": 8.4,
	    "YDS_1": 60.5,
	    "TDS_1": 0.3,
	    "FL": 0.2,
	    "FPTS": 34.7
	  },
	  {
	    "Player": "D.J. Foster",
	    "Team": "ARI",
	    "ATT": 14.7,
	    "YDS": 59,
	    "TDS": 0.3,
	    "REC": 12,
	    "YDS_1": 100.5,
	    "TDS_1": 0.5,
	    "FL": 0.1,
	    "FPTS": 32.3
	  },
	  {
	    "Player": "Jordan Scarlett",
	    "Team": "CAR",
	    "ATT": 29,
	    "YDS": 128.2,
	    "TDS": 0.9,
	    "REC": 7.6,
	    "YDS_1": 57.3,
	    "TDS_1": 0.2,
	    "FL": 0.2,
	    "FPTS": 32
	  },
	  {
	    "Player": "Jordan Wilkins",
	    "Team": "IND",
	    "ATT": 40,
	    "YDS": 182.6,
	    "TDS": 1,
	    "REC": 4.4,
	    "YDS_1": 28.8,
	    "TDS_1": 0.1,
	    "FL": 1.3,
	    "FPTS": 29.7
	  },
	  {
	    "Player": "Raheem Mostert",
	    "Team": "SF",
	    "ATT": 22.6,
	    "YDS": 143.6,
	    "TDS": 0.8,
	    "REC": 5.2,
	    "YDS_1": 38.3,
	    "TDS_1": 0.1,
	    "FL": 0.5,
	    "FPTS": 28
	  },
	  {
	    "Player": "Mike Weber",
	    "Team": "DAL",
	    "ATT": 31.2,
	    "YDS": 145,
	    "TDS": 1,
	    "REC": 3.6,
	    "YDS_1": 33.1,
	    "TDS_1": 0.2,
	    "FL": 0.4,
	    "FPTS": 27.9
	  },
	  {
	    "Player": "Taiwan Jones",
	    "Team": "HOU",
	    "ATT": 25.6,
	    "YDS": 88.9,
	    "TDS": 0.4,
	    "REC": 8,
	    "YDS_1": 67.1,
	    "TDS_1": 0.3,
	    "FL": 0.1,
	    "FPTS": 27.5
	  },
	  {
	    "Player": "J.D. McKissic",
	    "Team": "DET",
	    "ATT": 21.2,
	    "YDS": 82.9,
	    "TDS": 0.4,
	    "REC": 7.8,
	    "YDS_1": 56.5,
	    "TDS_1": 0.6,
	    "FL": 0.4,
	    "FPTS": 27.3
	  },
	  {
	    "Player": "Qadree Ollison",
	    "Team": "ATL",
	    "ATT": 33,
	    "YDS": 130.8,
	    "TDS": 0.9,
	    "REC": 4.3,
	    "YDS_1": 34.4,
	    "TDS_1": 0.2,
	    "FL": 0.2,
	    "FPTS": 27.2
	  },
	  {
	    "Player": "D'Ernest Johnson",
	    "Team": "CLE",
	    "ATT": 0,
	    "YDS": 89.1,
	    "TDS": 0.6,
	    "REC": 6.4,
	    "YDS_1": 52,
	    "TDS_1": 0.2,
	    "FL": 0.1,
	    "FPTS": 25.1
	  },
	  {
	    "Player": "Reggie Bonnafon",
	    "Team": "CAR",
	    "ATT": 15.8,
	    "YDS": 83.5,
	    "TDS": 0.6,
	    "REC": 6.7,
	    "YDS_1": 52,
	    "TDS_1": 0.2,
	    "FL": 0.2,
	    "FPTS": 24.9
	  },
	  {
	    "Player": "Elijhaa Penny",
	    "Team": "NYG",
	    "ATT": 6.3,
	    "YDS": 72.1,
	    "TDS": 0.6,
	    "REC": 6.9,
	    "YDS_1": 54.3,
	    "TDS_1": 0.2,
	    "FL": 0.1,
	    "FPTS": 24.1
	  },
	  {
	    "Player": "Mike Boone",
	    "Team": "MIN",
	    "ATT": 25.2,
	    "YDS": 107.4,
	    "TDS": 0.8,
	    "REC": 3.7,
	    "YDS_1": 27,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 21.9
	  },
	  {
	    "Player": "Myles Gaskin",
	    "Team": "MIA",
	    "ATT": 27.2,
	    "YDS": 108.3,
	    "TDS": 0.4,
	    "REC": 4.3,
	    "YDS_1": 35.4,
	    "TDS_1": 0.1,
	    "FL": 0.1,
	    "FPTS": 21.4
	  },
	  {
	    "Player": "Buddy Howell",
	    "Team": "HOU",
	    "ATT": 17.8,
	    "YDS": 77.4,
	    "TDS": 0.5,
	    "REC": 4.2,
	    "YDS_1": 46.2,
	    "TDS_1": 0.2,
	    "FL": 0.2,
	    "FPTS": 20.6
	  },
	  {
	    "Player": "James Develin",
	    "Team": "NE",
	    "ATT": 5.9,
	    "YDS": 22.2,
	    "TDS": 0.9,
	    "REC": 6.9,
	    "YDS_1": 47.8,
	    "TDS_1": 0.2,
	    "FL": 0.1,
	    "FPTS": 20.5
	  },
	  {
	    "Player": "Anthony Sherman",
	    "Team": "KC",
	    "ATT": 7.2,
	    "YDS": 20.5,
	    "TDS": 0.2,
	    "REC": 6.8,
	    "YDS_1": 67.8,
	    "TDS_1": 0.6,
	    "FL": 0.1,
	    "FPTS": 20.5
	  },
	  {
	    "Player": "Dwayne Washington",
	    "Team": "NO",
	    "ATT": 25.4,
	    "YDS": 111.9,
	    "TDS": 0.6,
	    "REC": 3,
	    "YDS_1": 20.9,
	    "TDS_1": 0.1,
	    "FL": 0,
	    "FPTS": 20.4
	  },
	  {
	    "Player": "Trayveon Williams",
	    "Team": "CIN",
	    "ATT": 15.4,
	    "YDS": 86.1,
	    "TDS": 0.4,
	    "REC": 4.4,
	    "YDS_1": 33.3,
	    "TDS_1": 0.1,
	    "FL": 0.1,
	    "FPTS": 19.4
	  },
	  {
	    "Player": "Josh Adams",
	    "Team": "NYJ",
	    "ATT": 23.4,
	    "YDS": 85.5,
	    "TDS": 0.6,
	    "REC": 3.9,
	    "YDS_1": 25.5,
	    "TDS_1": 0.1,
	    "FL": 0,
	    "FPTS": 19.4
	  },
	  {
	    "Player": "Travis Homer",
	    "Team": "SEA",
	    "ATT": 19.8,
	    "YDS": 90.2,
	    "TDS": 0.5,
	    "REC": 3.2,
	    "YDS_1": 29,
	    "TDS_1": 0.2,
	    "FL": 0.2,
	    "FPTS": 18.9
	  },
	  {
	    "Player": "Ameer Abdullah",
	    "Team": "MIN",
	    "ATT": 12.8,
	    "YDS": 41.3,
	    "TDS": 0.2,
	    "REC": 6.5,
	    "YDS_1": 47.7,
	    "TDS_1": 0.4,
	    "FL": 0.1,
	    "FPTS": 18.5
	  },
	  {
	    "Player": "Zach Line",
	    "Team": "NO",
	    "ATT": 9.5,
	    "YDS": 41.4,
	    "TDS": 0.3,
	    "REC": 4.9,
	    "YDS_1": 30.4,
	    "TDS_1": 0.7,
	    "FL": 0.1,
	    "FPTS": 18.2
	  },
	  {
	    "Player": "Brandon Bolden",
	    "Team": "NE",
	    "ATT": 11.6,
	    "YDS": 57.3,
	    "TDS": 1.4,
	    "REC": 1.4,
	    "YDS_1": 12.3,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 16.8
	  },
	  {
	    "Player": "Tyler Ervin",
	    "Team": "JAC",
	    "ATT": 9.1,
	    "YDS": 38.5,
	    "TDS": 0.3,
	    "REC": 4.3,
	    "YDS_1": 33.9,
	    "TDS_1": 0.1,
	    "FL": 0.1,
	    "FPTS": 13.5
	  },
	  {
	    "Player": "T.J. Logan",
	    "Team": "TB",
	    "ATT": 10,
	    "YDS": 38.2,
	    "TDS": 0.3,
	    "REC": 4.4,
	    "YDS_1": 30.2,
	    "TDS_1": 0.1,
	    "FL": 0.1,
	    "FPTS": 13.4
	  },
	  {
	    "Player": "Justin Davis",
	    "Team": "ARI",
	    "ATT": 17.8,
	    "YDS": 102.6,
	    "TDS": 0.5,
	    "REC": 0.5,
	    "YDS_1": 4.8,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 13.4
	  },
	  {
	    "Player": "Zach Zenner",
	    "Team": "ARI",
	    "ATT": 14,
	    "YDS": 69.5,
	    "TDS": 0.8,
	    "REC": 0.9,
	    "YDS_1": 7.7,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 12.9
	  },
	  {
	    "Player": "Julio Jones",
	    "Team": "ATL",
	    "REC": 105.8,
	    "YDS": 1525.8,
	    "TDS": 8.9,
	    "ATT": 1.5,
	    "YDS_1": 9.4,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 312
	  },
	  {
	    "Player": "DeAndre Hopkins",
	    "Team": "HOU",
	    "REC": 102.5,
	    "YDS": 1438.5,
	    "TDS": 10.3,
	    "ATT": 0.2,
	    "YDS_1": 1.2,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 307.4
	  },
	  {
	    "Player": "Davante Adams",
	    "Team": "GB",
	    "REC": 105.7,
	    "YDS": 1355.2,
	    "TDS": 10.4,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 303.6
	  },
	  {
	    "Player": "Michael Thomas",
	    "Team": "NO",
	    "REC": 111.7,
	    "YDS": 1347.9,
	    "TDS": 8.5,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.4,
	    "FPTS": 297
	  },
	  {
	    "Player": "JuJu Smith-Schuster",
	    "Team": "PIT",
	    "REC": 103.8,
	    "YDS": 1360.9,
	    "TDS": 8.9,
	    "ATT": 0.2,
	    "YDS_1": 1.7,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 293.2
	  },
	  {
	    "Player": "Tyreek Hill",
	    "Team": "KC",
	    "REC": 81.4,
	    "YDS": 1274.1,
	    "TDS": 8.8,
	    "ATT": 12.6,
	    "YDS_1": 93,
	    "TDS_1": 1,
	    "FL": 0.2,
	    "FPTS": 276.3
	  },
	  {
	    "Player": "Mike Evans",
	    "Team": "TB",
	    "REC": 84.8,
	    "YDS": 1366.8,
	    "TDS": 7.9,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 268
	  },
	  {
	    "Player": "Keenan Allen",
	    "Team": "LAC",
	    "REC": 97.7,
	    "YDS": 1254.2,
	    "TDS": 6.9,
	    "ATT": 3,
	    "YDS_1": 20.3,
	    "TDS_1": 0,
	    "FL": 0.4,
	    "FPTS": 265.8
	  },
	  {
	    "Player": "Odell Beckham Jr.",
	    "Team": "CLE",
	    "REC": 87.2,
	    "YDS": 1208.8,
	    "TDS": 9,
	    "ATT": 2.8,
	    "YDS_1": 11.6,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 263
	  },
	  {
	    "Player": "Julian Edelman",
	    "Team": "NE",
	    "REC": 93.6,
	    "YDS": 1120.2,
	    "TDS": 6.3,
	    "ATT": 7.6,
	    "YDS_1": 55.9,
	    "TDS_1": 0.3,
	    "FL": 0.3,
	    "FPTS": 249.8
	  },
	  {
	    "Player": "Adam Thielen",
	    "Team": "MIN",
	    "REC": 86.4,
	    "YDS": 1121.5,
	    "TDS": 6.6,
	    "ATT": 3.4,
	    "YDS_1": 20.5,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 239.8
	  },
	  {
	    "Player": "Amari Cooper",
	    "Team": "DAL",
	    "REC": 81.8,
	    "YDS": 1105.5,
	    "TDS": 7.3,
	    "ATT": 0.9,
	    "YDS_1": 5.2,
	    "TDS_1": 0,
	    "FL": 0.5,
	    "FPTS": 235.8
	  },
	  {
	    "Player": "Stefon Diggs",
	    "Team": "MIN",
	    "REC": 88.4,
	    "YDS": 1003.4,
	    "TDS": 7.3,
	    "ATT": 6.1,
	    "YDS_1": 30.9,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 235.5
	  },
	  {
	    "Player": "Brandin Cooks",
	    "Team": "LAR",
	    "REC": 74,
	    "YDS": 1114.2,
	    "TDS": 6.3,
	    "ATT": 6.6,
	    "YDS_1": 41.8,
	    "TDS_1": 0.5,
	    "FL": 0.2,
	    "FPTS": 230
	  },
	  {
	    "Player": "Robert Woods",
	    "Team": "LAR",
	    "REC": 76.4,
	    "YDS": 1037.8,
	    "TDS": 5.5,
	    "ATT": 10.5,
	    "YDS_1": 73.7,
	    "TDS_1": 0.7,
	    "FL": 0.3,
	    "FPTS": 223.8
	  },
	  {
	    "Player": "Tyler Lockett",
	    "Team": "SEA",
	    "REC": 67,
	    "YDS": 1067.8,
	    "TDS": 7.1,
	    "ATT": 8.4,
	    "YDS_1": 53.6,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 221.8
	  },
	  {
	    "Player": "T.Y. Hilton",
	    "Team": "IND",
	    "REC": 72.9,
	    "YDS": 1129.7,
	    "TDS": 5.8,
	    "ATT": 0,
	    "YDS_1": 0.1,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 220.3
	  },
	  {
	    "Player": "Kenny Golladay",
	    "Team": "DET",
	    "REC": 73.7,
	    "YDS": 1059.3,
	    "TDS": 6.2,
	    "ATT": 0.9,
	    "YDS_1": 5.4,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 216.7
	  },
	  {
	    "Player": "Tyler Boyd",
	    "Team": "CIN",
	    "REC": 76.6,
	    "YDS": 999.2,
	    "TDS": 5.8,
	    "ATT": 0.7,
	    "YDS_1": 3.5,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 211.2
	  },
	  {
	    "Player": "Chris Godwin",
	    "Team": "TB",
	    "REC": 71.9,
	    "YDS": 986.2,
	    "TDS": 6.3,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 207.8
	  },
	  {
	    "Player": "Cooper Kupp",
	    "Team": "LAR",
	    "REC": 69.4,
	    "YDS": 934.8,
	    "TDS": 6.7,
	    "ATT": 3.1,
	    "YDS_1": 19.2,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 204.7
	  },
	  {
	    "Player": "Alshon Jeffery",
	    "Team": "PHI",
	    "REC": 66.5,
	    "YDS": 906.6,
	    "TDS": 6.7,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 197.1
	  },
	  {
	    "Player": "Allen Robinson",
	    "Team": "CHI",
	    "REC": 67,
	    "YDS": 919.3,
	    "TDS": 6,
	    "ATT": 0.4,
	    "YDS_1": 1.5,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 195.7
	  },
	  {
	    "Player": "Mike Williams",
	    "Team": "LAC",
	    "REC": 60.2,
	    "YDS": 874.6,
	    "TDS": 7.3,
	    "ATT": 3.6,
	    "YDS_1": 19.2,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 193.5
	  },
	  {
	    "Player": "D.J. Moore",
	    "Team": "CAR",
	    "REC": 66.5,
	    "YDS": 887.1,
	    "TDS": 4.5,
	    "ATT": 13,
	    "YDS_1": 110.6,
	    "TDS_1": 0.1,
	    "FL": 0.5,
	    "FPTS": 193.2
	  },
	  {
	    "Player": "Robby Anderson",
	    "Team": "NYJ",
	    "REC": 61.1,
	    "YDS": 898.2,
	    "TDS": 6.5,
	    "ATT": 3.5,
	    "YDS_1": 16,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 191.2
	  },
	  {
	    "Player": "Sammy Watkins",
	    "Team": "KC",
	    "REC": 63.6,
	    "YDS": 891.8,
	    "TDS": 6.2,
	    "ATT": 2.1,
	    "YDS_1": 14,
	    "TDS_1": 0.1,
	    "FL": 0.3,
	    "FPTS": 190.9
	  },
	  {
	    "Player": "Jarvis Landry",
	    "Team": "CLE",
	    "REC": 70.5,
	    "YDS": 838.8,
	    "TDS": 5.2,
	    "ATT": 3.7,
	    "YDS_1": 25.5,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 188.6
	  },
	  {
	    "Player": "A.J. Green",
	    "Team": "CIN",
	    "REC": 61.7,
	    "YDS": 903.6,
	    "TDS": 5.9,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 187.2
	  },
	  {
	    "Player": "Calvin Ridley",
	    "Team": "ATL",
	    "REC": 63.7,
	    "YDS": 802.3,
	    "TDS": 6.5,
	    "ATT": 5.3,
	    "YDS_1": 29.6,
	    "TDS_1": 0.1,
	    "FL": 0.3,
	    "FPTS": 185.6
	  },
	  {
	    "Player": "Christian Kirk",
	    "Team": "ARI",
	    "REC": 64.9,
	    "YDS": 852.2,
	    "TDS": 4.8,
	    "ATT": 2,
	    "YDS_1": 11.4,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 179.8
	  },
	  {
	    "Player": "Dede Westbrook",
	    "Team": "JAC",
	    "REC": 69.2,
	    "YDS": 791.5,
	    "TDS": 4.9,
	    "ATT": 4.1,
	    "YDS_1": 25.9,
	    "TDS_1": 0,
	    "FL": 0.4,
	    "FPTS": 179.6
	  },
	  {
	    "Player": "Sterling Shepard",
	    "Team": "NYG",
	    "REC": 63.5,
	    "YDS": 839.6,
	    "TDS": 4.9,
	    "ATT": 2.1,
	    "YDS_1": 12.5,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 177.7
	  },
	  {
	    "Player": "Marvin Jones",
	    "Team": "DET",
	    "REC": 57.2,
	    "YDS": 845.4,
	    "TDS": 6,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 177.6
	  },
	  {
	    "Player": "Larry Fitzgerald",
	    "Team": "ARI",
	    "REC": 68.2,
	    "YDS": 759.3,
	    "TDS": 5.1,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 174.2
	  },
	  {
	    "Player": "Dante Pettis",
	    "Team": "SF",
	    "REC": 58.6,
	    "YDS": 807.6,
	    "TDS": 5.7,
	    "ATT": 0.3,
	    "YDS_1": 0.9,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 173.2
	  },
	  {
	    "Player": "Josh Gordon",
	    "Team": "SEA",
	    "REC": 53.7,
	    "YDS": 861.4,
	    "TDS": 5.6,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 172.8
	  },
	  {
	    "Player": "Corey Davis",
	    "Team": "TEN",
	    "REC": 61.7,
	    "YDS": 814.3,
	    "TDS": 4.4,
	    "ATT": 3.7,
	    "YDS_1": 23.3,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 171.3
	  },
	  {
	    "Player": "Emmanuel Sanders",
	    "Team": "SF",
	    "REC": 64.3,
	    "YDS": 782.4,
	    "TDS": 4.3,
	    "ATT": 2.4,
	    "YDS_1": 11.1,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 169.4
	  },
	  {
	    "Player": "Curtis Samuel",
	    "Team": "CAR",
	    "REC": 57.2,
	    "YDS": 716.6,
	    "TDS": 4.8,
	    "ATT": 9.6,
	    "YDS_1": 71.9,
	    "TDS_1": 0.5,
	    "FL": 0.2,
	    "FPTS": 167.7
	  },
	  {
	    "Player": "Will Fuller",
	    "Team": "HOU",
	    "REC": 52.4,
	    "YDS": 762.6,
	    "TDS": 5.5,
	    "ATT": 0.2,
	    "YDS_1": 1,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 161.5
	  },
	  {
	    "Player": "Mohamed Sanu",
	    "Team": "NE",
	    "REC": 59.3,
	    "YDS": 723.5,
	    "TDS": 3.7,
	    "ATT": 3,
	    "YDS_1": 22.2,
	    "TDS_1": 0.1,
	    "FL": 0.3,
	    "FPTS": 156.1
	  },
	  {
	    "Player": "Jamison Crowder",
	    "Team": "NYJ",
	    "REC": 58.6,
	    "YDS": 689.3,
	    "TDS": 4,
	    "ATT": 1.8,
	    "YDS_1": 10.8,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 152.3
	  },
	  {
	    "Player": "Courtland Sutton",
	    "Team": "DEN",
	    "REC": 49.4,
	    "YDS": 710.2,
	    "TDS": 4.5,
	    "ATT": 0.2,
	    "YDS_1": 1.9,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 147.5
	  },
	  {
	    "Player": "Albert Wilson",
	    "Team": "MIA",
	    "REC": 53.4,
	    "YDS": 662.5,
	    "TDS": 4,
	    "ATT": 5.4,
	    "YDS_1": 31.5,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 147
	  },
	  {
	    "Player": "DeSean Jackson",
	    "Team": "PHI",
	    "REC": 44.4,
	    "YDS": 735,
	    "TDS": 4.3,
	    "ATT": 3.5,
	    "YDS_1": 25,
	    "TDS_1": 0.1,
	    "FL": 0.1,
	    "FPTS": 146.9
	  },
	  {
	    "Player": "Michael Gallup",
	    "Team": "DAL",
	    "REC": 47.5,
	    "YDS": 708.4,
	    "TDS": 4.3,
	    "ATT": 0,
	    "YDS_1": 0.2,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 144.1
	  },
	  {
	    "Player": "Marquez Valdes-Scantling",
	    "Team": "GB",
	    "REC": 49.1,
	    "YDS": 677.7,
	    "TDS": 4.3,
	    "ATT": 1.8,
	    "YDS_1": 10.5,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 143.5
	  },
	  {
	    "Player": "Donte Moncrief",
	    "Team": "CAR",
	    "REC": 50.6,
	    "YDS": 654,
	    "TDS": 4.5,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 142.5
	  },
	  {
	    "Player": "Geronimo Allison",
	    "Team": "GB",
	    "REC": 50.7,
	    "YDS": 671.7,
	    "TDS": 4.1,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 141.9
	  },
	  {
	    "Player": "Tyrell Williams",
	    "Team": "OAK",
	    "REC": 49.4,
	    "YDS": 694.1,
	    "TDS": 3.9,
	    "ATT": 0.4,
	    "YDS_1": 1.1,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 141.7
	  },
	  {
	    "Player": "Golden Tate",
	    "Team": "NYG",
	    "REC": 54.9,
	    "YDS": 631.8,
	    "TDS": 3.3,
	    "ATT": 1.9,
	    "YDS_1": 14,
	    "TDS_1": 0.1,
	    "FL": 0.5,
	    "FPTS": 138.9
	  },
	  {
	    "Player": "Ted Ginn",
	    "Team": "NO",
	    "REC": 44.2,
	    "YDS": 644.4,
	    "TDS": 3.6,
	    "ATT": 8,
	    "YDS_1": 54.3,
	    "TDS_1": 0.3,
	    "FL": 0.2,
	    "FPTS": 137.3
	  },
	  {
	    "Player": "D.K. Metcalf",
	    "Team": "SEA",
	    "REC": 45.7,
	    "YDS": 652.1,
	    "TDS": 4.5,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.3,
	    "FPTS": 137.1
	  },
	  {
	    "Player": "Paul Richardson",
	    "Team": "WAS",
	    "REC": 47.3,
	    "YDS": 675.4,
	    "TDS": 3.4,
	    "ATT": 1.9,
	    "YDS_1": 10.7,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 136.5
	  },
	  {
	    "Player": "DaeSean Hamilton",
	    "Team": "DEN",
	    "REC": 54,
	    "YDS": 601.6,
	    "TDS": 3.5,
	    "ATT": 0,
	    "YDS_1": 0.2,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 134.9
	  },
	  {
	    "Player": "John Brown",
	    "Team": "BUF",
	    "REC": 43.4,
	    "YDS": 651.8,
	    "TDS": 4.3,
	    "ATT": 0.2,
	    "YDS_1": 0.8,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 134.1
	  },
	  {
	    "Player": "Adam Humphries",
	    "Team": "TEN",
	    "REC": 52.7,
	    "YDS": 610.6,
	    "TDS": 3.2,
	    "ATT": 1.7,
	    "YDS_1": 9.3,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 134
	  },
	  {
	    "Player": "Devante Parker",
	    "Team": "MIA",
	    "REC": 50.1,
	    "YDS": 634.4,
	    "TDS": 3.2,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 132.4
	  },
	  {
	    "Player": "Anthony Miller",
	    "Team": "CHI",
	    "REC": 44.1,
	    "YDS": 570.2,
	    "TDS": 3.9,
	    "ATT": 2.3,
	    "YDS_1": 11.7,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 125.6
	  },
	  {
	    "Player": "Danny Amendola",
	    "Team": "DET",
	    "REC": 53.3,
	    "YDS": 538.5,
	    "TDS": 2.7,
	    "ATT": 0.9,
	    "YDS_1": 4.6,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 123.8
	  },
	  {
	    "Player": "Keke Coutee",
	    "Team": "HOU",
	    "REC": 48.8,
	    "YDS": 540.6,
	    "TDS": 3.1,
	    "ATT": 3.7,
	    "YDS_1": 18.1,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 123.2
	  },
	  {
	    "Player": "James Washington",
	    "Team": "PIT",
	    "REC": 41.7,
	    "YDS": 591.1,
	    "TDS": 3.7,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 122.9
	  },
	  {
	    "Player": "Cole Beasley",
	    "Team": "BUF",
	    "REC": 48.8,
	    "YDS": 564.1,
	    "TDS": 2.9,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 122.3
	  },
	  {
	    "Player": "Taylor Gabriel",
	    "Team": "CHI",
	    "REC": 47,
	    "YDS": 538.2,
	    "TDS": 2.6,
	    "ATT": 4.4,
	    "YDS_1": 27.5,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 119
	  },
	  {
	    "Player": "Willie Snead",
	    "Team": "BAL",
	    "REC": 47.4,
	    "YDS": 540.5,
	    "TDS": 2.4,
	    "ATT": 0.5,
	    "YDS_1": 1.4,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 115.7
	  },
	  {
	    "Player": "Terry McLaurin",
	    "Team": "WAS",
	    "REC": 42.5,
	    "YDS": 543.3,
	    "TDS": 3.1,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 114.9
	  },
	  {
	    "Player": "Quincy Enunwa",
	    "Team": "NYJ",
	    "REC": 43.7,
	    "YDS": 548.5,
	    "TDS": 2.7,
	    "ATT": 0.5,
	    "YDS_1": 1.1,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 114.7
	  },
	  {
	    "Player": "Marquise Goodwin",
	    "Team": "SF",
	    "REC": 35.7,
	    "YDS": 553.2,
	    "TDS": 3.5,
	    "ATT": 2.5,
	    "YDS_1": 16.1,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 113.6
	  },
	  {
	    "Player": "Zay Jones",
	    "Team": "OAK",
	    "REC": 39.9,
	    "YDS": 524.8,
	    "TDS": 3.5,
	    "ATT": 0.5,
	    "YDS_1": 2.9,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 113.4
	  },
	  {
	    "Player": "Randall Cobb",
	    "Team": "DAL",
	    "REC": 45.8,
	    "YDS": 494.6,
	    "TDS": 2.6,
	    "ATT": 2,
	    "YDS_1": 10.4,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 111.8
	  },
	  {
	    "Player": "Marquise Brown",
	    "Team": "BAL",
	    "REC": 37.6,
	    "YDS": 527.8,
	    "TDS": 2.9,
	    "ATT": 1.8,
	    "YDS_1": 10.9,
	    "TDS_1": 0.1,
	    "FL": 0.2,
	    "FPTS": 109
	  },
	  {
	    "Player": "Devin Funchess",
	    "Team": "IND",
	    "REC": 38,
	    "YDS": 487.3,
	    "TDS": 3.7,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 108.7
	  },
	  {
	    "Player": "Trey Quinn",
	    "Team": "WAS",
	    "REC": 39.9,
	    "YDS": 462.8,
	    "TDS": 2.7,
	    "ATT": 1.4,
	    "YDS_1": 7.9,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 102.8
	  },
	  {
	    "Player": "Robert Foster",
	    "Team": "BUF",
	    "REC": 31.1,
	    "YDS": 503.5,
	    "TDS": 3.4,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 101.6
	  },
	  {
	    "Player": "Jakeem Grant",
	    "Team": "MIA",
	    "REC": 37.2,
	    "YDS": 483.2,
	    "TDS": 2.6,
	    "ATT": 0.6,
	    "YDS_1": 1.2,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 101.2
	  },
	  {
	    "Player": "Rashard Higgins",
	    "Team": "CLE",
	    "REC": 35.2,
	    "YDS": 469.7,
	    "TDS": 3.1,
	    "ATT": 0.1,
	    "YDS_1": 0.6,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 100.5
	  },
	  {
	    "Player": "Tre'Quan Smith",
	    "Team": "NO",
	    "REC": 32.8,
	    "YDS": 471.9,
	    "TDS": 3,
	    "ATT": 0.1,
	    "YDS_1": 0.4,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 98
	  },
	  {
	    "Player": "Chris Conley",
	    "Team": "JAC",
	    "REC": 34.5,
	    "YDS": 437.8,
	    "TDS": 2.6,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.2,
	    "FPTS": 93.3
	  },
	  {
	    "Player": "D.J. Chark",
	    "Team": "JAC",
	    "REC": 35.9,
	    "YDS": 442.5,
	    "TDS": 2.2,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 93.2
	  },
	  {
	    "Player": "Deebo Samuel",
	    "Team": "SF",
	    "REC": 35.5,
	    "YDS": 423.4,
	    "TDS": 2.3,
	    "ATT": 1.3,
	    "YDS_1": 7.6,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 92.7
	  },
	  {
	    "Player": "Marqise Lee",
	    "Team": "JAC",
	    "REC": 33.2,
	    "YDS": 434.1,
	    "TDS": 2.3,
	    "ATT": 2.5,
	    "YDS_1": 17.5,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 92.1
	  },
	  {
	    "Player": "Nelson Agholor",
	    "Team": "PHI",
	    "REC": 32.4,
	    "YDS": 402.4,
	    "TDS": 2.8,
	    "ATT": 3.2,
	    "YDS_1": 20.9,
	    "TDS_1": 0.1,
	    "FL": 0.1,
	    "FPTS": 91.9
	  },
	  {
	    "Player": "A.J. Brown",
	    "Team": "TEN",
	    "REC": 34,
	    "YDS": 429.8,
	    "TDS": 2.3,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 90.5
	  },
	  {
	    "Player": "Breshad Perriman",
	    "Team": "TB",
	    "REC": 28.8,
	    "YDS": 434.3,
	    "TDS": 2.6,
	    "ATT": 1.4,
	    "YDS_1": 7.9,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 88.7
	  },
	  {
	    "Player": "Hunter Renfrow",
	    "Team": "OAK",
	    "REC": 36,
	    "YDS": 396.3,
	    "TDS": 2,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 87.6
	  },
	  {
	    "Player": "Demaryius Thomas",
	    "Team": "NYJ",
	    "REC": 32.7,
	    "YDS": 404.7,
	    "TDS": 2.3,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 86.9
	  },
	  {
	    "Player": "Miles Boykin",
	    "Team": "BAL",
	    "REC": 27.7,
	    "YDS": 395.7,
	    "TDS": 2.3,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 81.1
	  },
	  {
	    "Player": "Parris Campbell",
	    "Team": "IND",
	    "REC": 29.3,
	    "YDS": 362,
	    "TDS": 1.9,
	    "ATT": 2.5,
	    "YDS_1": 15.2,
	    "TDS_1": 0.1,
	    "FL": 0.1,
	    "FPTS": 78.8
	  },
	  {
	    "Player": "Preston Williams",
	    "Team": "MIA",
	    "REC": 28.7,
	    "YDS": 380.7,
	    "TDS": 1.8,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 77.6
	  },
	  {
	    "Player": "Kenny Stills",
	    "Team": "HOU",
	    "REC": 23.8,
	    "YDS": 352.7,
	    "TDS": 2.4,
	    "ATT": 0,
	    "YDS_1": -0.1,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 73.1
	  },
	  {
	    "Player": "John Ross",
	    "Team": "CIN",
	    "REC": 25.9,
	    "YDS": 330.9,
	    "TDS": 2.2,
	    "ATT": 2,
	    "YDS_1": 9.9,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 72.9
	  },
	  {
	    "Player": "Travis Benjamin",
	    "Team": "LAC",
	    "REC": 21.5,
	    "YDS": 337.4,
	    "TDS": 2,
	    "ATT": 5.9,
	    "YDS_1": 36.7,
	    "TDS_1": 0.4,
	    "FL": 0.1,
	    "FPTS": 72.7
	  },
	  {
	    "Player": "Andy Isabella",
	    "Team": "ARI",
	    "REC": 25.8,
	    "YDS": 332.6,
	    "TDS": 2.1,
	    "ATT": 1.3,
	    "YDS_1": 8.1,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 72.2
	  },
	  {
	    "Player": "Mecole Hardman",
	    "Team": "KC",
	    "REC": 21.9,
	    "YDS": 303.7,
	    "TDS": 2.1,
	    "ATT": 5.8,
	    "YDS_1": 37.7,
	    "TDS_1": 0.5,
	    "FL": 0.1,
	    "FPTS": 71.5
	  },
	  {
	    "Player": "Cody Latimer",
	    "Team": "NYG",
	    "REC": 23.5,
	    "YDS": 352.2,
	    "TDS": 2,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 70.6
	  },
	  {
	    "Player": "KeeSean Johnson",
	    "Team": "ARI",
	    "REC": 25.1,
	    "YDS": 335.2,
	    "TDS": 2,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0.1,
	    "FPTS": 70.3
	  },
	  {
	    "Player": "Demarcus Robinson",
	    "Team": "KC",
	    "REC": 23.2,
	    "YDS": 321.1,
	    "TDS": 2.4,
	    "ATT": 0,
	    "YDS_1": 0,
	    "TDS_1": 0,
	    "FL": 0,
	    "FPTS": 69.6
	  },
	  {
	    "Player": "Travis Kelce",
	    "Team": "KC",
	    "REC": 98.2,
	    "YDS": 1236.1,
	    "TDS": 9.5,
	    "FL": 0.6,
	    "FPTS": 277.8
	  },
	  {
	    "Player": "George Kittle",
	    "Team": "SF",
	    "REC": 85.7,
	    "YDS": 1180.3,
	    "TDS": 6.6,
	    "FL": 0.3,
	    "FPTS": 242.7
	  },
	  {
	    "Player": "Zach Ertz",
	    "Team": "PHI",
	    "REC": 90.5,
	    "YDS": 956,
	    "TDS": 6.9,
	    "FL": 0.5,
	    "FPTS": 226.7
	  },
	  {
	    "Player": "Evan Engram",
	    "Team": "NYG",
	    "REC": 68.8,
	    "YDS": 824.5,
	    "TDS": 5.4,
	    "FL": 0.4,
	    "FPTS": 182.7
	  },
	  {
	    "Player": "Jared Cook",
	    "Team": "NO",
	    "REC": 63.3,
	    "YDS": 794.5,
	    "TDS": 6,
	    "FL": 0.3,
	    "FPTS": 177.8
	  },
	  {
	    "Player": "O.J. Howard",
	    "Team": "TB",
	    "REC": 57.2,
	    "YDS": 816.1,
	    "TDS": 6.5,
	    "FL": 0.5,
	    "FPTS": 176.6
	  },
	  {
	    "Player": "Hunter Henry",
	    "Team": "LAC",
	    "REC": 54.9,
	    "YDS": 696.3,
	    "TDS": 6,
	    "FL": 0.3,
	    "FPTS": 159.6
	  },
	  {
	    "Player": "Vance McDonald",
	    "Team": "PIT",
	    "REC": 59.6,
	    "YDS": 677.7,
	    "TDS": 4.8,
	    "FL": 0.5,
	    "FPTS": 155.1
	  },
	  {
	    "Player": "Austin Hooper",
	    "Team": "ATL",
	    "REC": 62.4,
	    "YDS": 608.3,
	    "TDS": 4.4,
	    "FL": 0.3,
	    "FPTS": 148.9
	  },
	  {
	    "Player": "Jordan Reed",
	    "Team": "WAS",
	    "REC": 62.8,
	    "YDS": 631.9,
	    "TDS": 3.8,
	    "FL": 0.5,
	    "FPTS": 147.6
	  },
	  {
	    "Player": "David Njoku",
	    "Team": "CLE",
	    "REC": 53.6,
	    "YDS": 629.7,
	    "TDS": 4.8,
	    "FL": 0.3,
	    "FPTS": 144.8
	  },
	  {
	    "Player": "Delanie Walker",
	    "Team": "TEN",
	    "REC": 53.1,
	    "YDS": 587.3,
	    "TDS": 3.8,
	    "FL": 0.5,
	    "FPTS": 133.9
	  },
	  {
	    "Player": "Eric Ebron",
	    "Team": "IND",
	    "REC": 48.4,
	    "YDS": 545.8,
	    "TDS": 5.2,
	    "FL": 0.4,
	    "FPTS": 133.1
	  },
	  {
	    "Player": "Jimmy Graham",
	    "Team": "GB",
	    "REC": 52.4,
	    "YDS": 563.6,
	    "TDS": 4.1,
	    "FL": 0.3,
	    "FPTS": 132.8
	  },
	  {
	    "Player": "Mark Andrews",
	    "Team": "BAL",
	    "REC": 45.9,
	    "YDS": 603.1,
	    "TDS": 3.9,
	    "FL": 0.2,
	    "FPTS": 129.4
	  },
	  {
	    "Player": "Trey Burton",
	    "Team": "CHI",
	    "REC": 48.5,
	    "YDS": 526.6,
	    "TDS": 4.4,
	    "FL": 0.4,
	    "FPTS": 127
	  },
	  {
	    "Player": "T.J. Hockenson",
	    "Team": "DET",
	    "REC": 50.2,
	    "YDS": 543.2,
	    "TDS": 3.9,
	    "FL": 0.9,
	    "FPTS": 126.3
	  },
	  {
	    "Player": "Greg Olsen",
	    "Team": "CAR",
	    "REC": 45.7,
	    "YDS": 534.9,
	    "TDS": 4.5,
	    "FL": 0.2,
	    "FPTS": 125.8
	  },
	  {
	    "Player": "Kyle Rudolph",
	    "Team": "MIN",
	    "REC": 50.8,
	    "YDS": 495.6,
	    "TDS": 4,
	    "FL": 0.2,
	    "FPTS": 124
	  },
	  {
	    "Player": "Jack Doyle",
	    "Team": "IND",
	    "REC": 52.9,
	    "YDS": 496.8,
	    "TDS": 3.8,
	    "FL": 0.9,
	    "FPTS": 123.4
	  },
	  {
	    "Player": "Chris Herndon IV",
	    "Team": "NYJ",
	    "REC": 38.5,
	    "YDS": 473.8,
	    "TDS": 4.6,
	    "FL": 0.4,
	    "FPTS": 112.6
	  },
	  {
	    "Player": "Jason Witten",
	    "Team": "DAL",
	    "REC": 45.9,
	    "YDS": 448.8,
	    "TDS": 3.4,
	    "FL": 0.3,
	    "FPTS": 110.7
	  },
	  {
	    "Player": "Noah Fant",
	    "Team": "DEN",
	    "REC": 43.2,
	    "YDS": 479.7,
	    "TDS": 3.3,
	    "FL": 0.7,
	    "FPTS": 109.5
	  },
	  {
	    "Player": "Tyler Eifert",
	    "Team": "CIN",
	    "REC": 40.1,
	    "YDS": 445.3,
	    "TDS": 3.4,
	    "FL": 0.2,
	    "FPTS": 104.9
	  },
	  {
	    "Player": "Dallas Goedert",
	    "Team": "PHI",
	    "REC": 34.2,
	    "YDS": 356.3,
	    "TDS": 4,
	    "FL": 0.2,
	    "FPTS": 93.2
	  },
	  {
	    "Player": "Darren Waller",
	    "Team": "OAK",
	    "REC": 34.3,
	    "YDS": 374,
	    "TDS": 3.2,
	    "FL": 0.2,
	    "FPTS": 90.2
	  },
	  {
	    "Player": "Will Dissly",
	    "Team": "SEA",
	    "REC": 28.6,
	    "YDS": 383.9,
	    "TDS": 3.4,
	    "FL": 0.2,
	    "FPTS": 87.1
	  },
	  {
	    "Player": "Geoff Swaim",
	    "Team": "JAC",
	    "REC": 35.6,
	    "YDS": 349.3,
	    "TDS": 2,
	    "FL": 0.2,
	    "FPTS": 82.3
	  },
	  {
	    "Player": "Cameron Brate",
	    "Team": "TB",
	    "REC": 30.1,
	    "YDS": 315.7,
	    "TDS": 3.4,
	    "FL": 0.5,
	    "FPTS": 81.1
	  },
	  {
	    "Player": "Vernon Davis",
	    "Team": "WAS",
	    "REC": 29.1,
	    "YDS": 366.4,
	    "TDS": 2.4,
	    "FL": 0.2,
	    "FPTS": 79.5
	  },
	  {
	    "Player": "Mike Gesicki",
	    "Team": "MIA",
	    "REC": 33.5,
	    "YDS": 330.4,
	    "TDS": 1.9,
	    "FL": 0.5,
	    "FPTS": 76.7
	  },
	  {
	    "Player": "Gerald Everett",
	    "Team": "LAR",
	    "REC": 28.4,
	    "YDS": 307.2,
	    "TDS": 2.6,
	    "FL": 0.2,
	    "FPTS": 74.2
	  },
	  {
	    "Player": "Charles Clay",
	    "Team": "ARI",
	    "REC": 30.2,
	    "YDS": 277.5,
	    "TDS": 1.8,
	    "FL": 0.3,
	    "FPTS": 68.1
	  },
	  {
	    "Player": "Ian Thomas",
	    "Team": "CAR",
	    "REC": 27.2,
	    "YDS": 276.5,
	    "TDS": 2,
	    "FL": 0.2,
	    "FPTS": 66.5
	  },
	  {
	    "Player": "Irv Smith Jr.",
	    "Team": "MIN",
	    "REC": 26.5,
	    "YDS": 274.8,
	    "TDS": 2,
	    "FL": 0.5,
	    "FPTS": 64.9
	  },
	  {
	    "Player": "Benjamin Watson",
	    "Team": "NE",
	    "REC": 23.7,
	    "YDS": 268.1,
	    "TDS": 2.1,
	    "FL": 0.1,
	    "FPTS": 62.7
	  },
    ];
    return {players, teams, stats};
  }
}




